package types

import (
	fmt "fmt"
	"testing"

	tmrand "github.com/cometbft/cometbft/libs/rand"
	sdkerrors "github.com/cosmos/cosmos-sdk/types/errors"
	"github.com/stretchr/testify/require"
	testconstants "github.com/zigbee-alliance/distributed-compliance-ledger/integration_tests/constants"
	"github.com/zigbee-alliance/distributed-compliance-ledger/testutil/sample"
	"github.com/zigbee-alliance/distributed-compliance-ledger/utils/validator"
)

func TestMsgProvisionModel_ValidateBasic(t *testing.T) {
	negativeTests := []struct {
		name string
		msg  MsgProvisionModel
		err  error
	}{
		{
			name: "invalid address",
			msg: MsgProvisionModel{
				Signer:                "invalid_address",
				SoftwareVersionString: testconstants.SoftwareVersionString,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       testconstants.SoftwareVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				SchemaVersion:         1,
			},
			err: sdkerrors.ErrInvalidAddress,
		},
		{
			name: "vid is 0",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Vid:                   0,
				Pid:                   1,
				SoftwareVersionString: testconstants.SoftwareVersionString,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       testconstants.SoftwareVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				SchemaVersion:         1,
			},
			err: validator.ErrFieldLowerBoundViolated,
		},
		{
			name: "vid < 0",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Vid:                   -1,
				Pid:                   1,
				SoftwareVersionString: testconstants.SoftwareVersionString,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       testconstants.SoftwareVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
			err: validator.ErrFieldLowerBoundViolated,
		},
		{
			name: "vid > 65535",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Vid:                   65536,
				Pid:                   1,
				SoftwareVersionString: testconstants.SoftwareVersionString,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       testconstants.SoftwareVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
			err: validator.ErrFieldUpperBoundViolated,
		},
		{
			name: "pid is 0",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   0,
				Vid:                   1,
				SoftwareVersionString: testconstants.SoftwareVersionString,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       testconstants.SoftwareVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
			err: validator.ErrFieldLowerBoundViolated,
		},
		{
			name: "pid < 0",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   -1,
				Vid:                   1,
				SoftwareVersionString: testconstants.SoftwareVersionString,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       testconstants.SoftwareVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
			err: validator.ErrFieldLowerBoundViolated,
		},
		{
			name: "pid > 65535",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   65536,
				Vid:                   1,
				SoftwareVersionString: testconstants.SoftwareVersionString,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       testconstants.SoftwareVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
			err: validator.ErrFieldUpperBoundViolated,
		},
		{
			name: "cd version number > 65535",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				CDVersionNumber:       65536,
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.SoftwareVersionString,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       testconstants.SoftwareVersion,
				Reason:                testconstants.Reason,
				SchemaVersion:         1,
			},
			err: validator.ErrFieldUpperBoundViolated,
		},
		{
			name: "provisional date not set",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.SoftwareVersionString,
				ProvisionalDate:       "",
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
			err: validator.ErrRequiredFieldMissing,
		},
		{
			name: "certification type not set",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.SoftwareVersionString,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     "",
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				SchemaVersion:         1,
			},
			err: validator.ErrRequiredFieldMissing,
		},
		{
			name: "invalid certification type",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.SoftwareVersionString,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     "invalid type",
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
			err: ErrInvalidCertificationType,
		},
		{
			name: "provisional date is not RFC3339",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.SoftwareVersionString,
				ProvisionalDate:       "2020-01-01",
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
			err: ErrInvalidTestDateFormat,
		},
		{
			name: "software version string len > 64",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: fmt.Sprintf("1.%063d", 0),
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
			err: validator.ErrFieldMaxLengthExceeded,
		},
		{
			name: "reason len > 20480 (20 KB)",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                tmrand.Str(20481),
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
			err: validator.ErrFieldMaxLengthExceeded,
		},
		{
			name: "programTypeVersion > 64",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				ProgramTypeVersion:    tmrand.Str(65),
				SchemaVersion:         1,
			},
			err: validator.ErrFieldMaxLengthExceeded,
		},
		{
			name: "CDCertificateId > 19",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       tmrand.Str(20),
				SchemaVersion:         1,
			},
			err: validator.ErrFieldMaxLengthExceeded,
		},
		{
			name: "CDCertificateId < 19",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       tmrand.Str(18),
				SchemaVersion:         1,
			},
			err: validator.ErrFieldMinLengthNotReached,
		},
		{
			name: "familyID > 64",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       tmrand.Str(20),
				FamilyId:              tmrand.Str(65),
				SchemaVersion:         1,
			},
			err: validator.ErrFieldMaxLengthExceeded,
		},
		{
			name: "SupportedClusters > 128",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SupportedClusters:     tmrand.Str(129),
				SchemaVersion:         1,
			},
			err: validator.ErrFieldMaxLengthExceeded,
		},
		{
			name: "SupportedClusters not hex",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SupportedClusters:     "Some Supported Clusters",
				SchemaVersion:         1,
			},
			err: ErrInvalidSupportedClusters,
		},
		{
			name: "SupportedClusters missing 0x prefix",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SupportedClusters:     "0003,0004",
				SchemaVersion:         1,
			},
			err: ErrInvalidSupportedClusters,
		},
		{
			name: "SupportedClusters more than 4 hex digits",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SupportedClusters:     "0x00003",
				SchemaVersion:         1,
			},
			err: ErrInvalidSupportedClusters,
		},
		{
			name: "SupportedClusters mixes valid and invalid entry",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SupportedClusters:     "0x0003,zzz",
				SchemaVersion:         1,
			},
			err: ErrInvalidSupportedClusters,
		},
		{
			name: "SupportedClusters with whitespace after comma",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SupportedClusters:     "0x0003, 0x0004",
				SchemaVersion:         1,
			},
			err: ErrInvalidSupportedClusters,
		},
		{
			name: "SupportedClusters contains duplicate",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SupportedClusters:     "0x0003,0x0003",
				SchemaVersion:         1,
			},
			err: ErrInvalidSupportedClusters,
		},
		{
			name: "SupportedClusters case-insensitive duplicate",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SupportedClusters:     "0x000A,0x000a",
				SchemaVersion:         1,
			},
			err: ErrInvalidSupportedClusters,
		},
		{
			name: "SupportedClusters with trailing comma",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SupportedClusters:     "0x0003,",
				SchemaVersion:         1,
			},
			err: ErrInvalidSupportedClusters,
		},
		{
			name: "compliancePlatformUsed > 64",
			msg: MsgProvisionModel{
				Signer:                   sample.AccAddress(),
				Pid:                      1,
				Vid:                      1,
				SoftwareVersionString:    testconstants.TestDate,
				ProvisionalDate:          testconstants.CertificationDate,
				CertificationType:        testconstants.CertificationType,
				SpecificationVersion:     testconstants.SpecificationVersion,
				CDVersionNumber:          uint32(testconstants.CdVersionNumber),
				Reason:                   testconstants.Reason,
				CDCertificateId:          testconstants.CDCertificateID,
				CompliantPlatformVersion: tmrand.Str(65),
				SchemaVersion:            1,
			},
			err: validator.ErrFieldMaxLengthExceeded,
		},
		{
			name: "compliancePlatformVersion > 64",
			msg: MsgProvisionModel{
				Signer:                   sample.AccAddress(),
				Pid:                      1,
				Vid:                      1,
				SoftwareVersionString:    testconstants.TestDate,
				ProvisionalDate:          testconstants.CertificationDate,
				CertificationType:        testconstants.CertificationType,
				SpecificationVersion:     testconstants.SpecificationVersion,
				CDVersionNumber:          uint32(testconstants.CdVersionNumber),
				Reason:                   testconstants.Reason,
				CDCertificateId:          testconstants.CDCertificateID,
				CompliantPlatformVersion: tmrand.Str(65),
				SchemaVersion:            1,
			},
			err: validator.ErrFieldMaxLengthExceeded,
		},
		{
			name: "OSVersion > 64",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				OSVersion:             tmrand.Str(65),
				SchemaVersion:         1,
			},
			err: validator.ErrFieldMaxLengthExceeded,
		},
		{
			name: "certificationRoute > 64",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				CertificationRoute:    tmrand.Str(65),
				SchemaVersion:         1,
			},
			err: validator.ErrFieldMaxLengthExceeded,
		},
		{
			name: "invalid certificationRoute",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				SoftwareVersionString: testconstants.TestDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				CertificationRoute:    "unsupported certification route",
				SchemaVersion:         1,
			},
			err: ErrInvalidCertificationRoute,
		},
		{
			name: "programType > 64",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				ProgramType:           tmrand.Str(65),
				SchemaVersion:         1,
			},
			err: validator.ErrFieldMaxLengthExceeded,
		},
		{
			name: "programType unsupported value",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				ProgramType:           "pType",
				SchemaVersion:         1,
			},
			err: ErrInvalidProgramType,
		},
		{
			name: "programType wrong case",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				ProgramType:           "EndProduct",
				SchemaVersion:         1,
			},
			err: ErrInvalidProgramType,
		},
		{
			name: "programTypeVersion set when programType is empty",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				ProgramType:           "",
				ProgramTypeVersion:    testconstants.ProgramTypeVersion,
				SchemaVersion:         1,
			},
			err: ErrProgramTypeVersionWithoutProgramType,
		},
		{
			name: "transport > 64",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				Transport:             tmrand.Str(65),
				SchemaVersion:         1,
			},
			err: validator.ErrFieldMaxLengthExceeded,
		},
		{
			name: "Transport unsupported value",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				Transport:             "lora",
				SchemaVersion:         1,
			},
			err: ErrInvalidTransport,
		},
		{
			name: "Transport mixes valid and unsupported value",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				Transport:             "wi-fi,lora",
				SchemaVersion:         1,
			},
			err: ErrInvalidTransport,
		},
		{
			name: "Transport with whitespace after comma",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				Transport:             "wi-fi, ethernet",
				SchemaVersion:         1,
			},
			err: ErrInvalidTransport,
		},
		{
			name: "Transport contains duplicate",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				Transport:             "wi-fi,wi-fi",
				SchemaVersion:         1,
			},
			err: ErrInvalidTransport,
		},
		{
			name: "Transport with leading comma",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				Transport:             ",wi-fi",
				SchemaVersion:         1,
			},
			err: ErrInvalidTransport,
		},
		{
			name: "Transport with trailing comma",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				Transport:             "wi-fi,",
				SchemaVersion:         1,
			},
			err: ErrInvalidTransport,
		},
		{
			name: "Transport with empty entry between",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				Transport:             "wi-fi,,ethernet",
				SchemaVersion:         1,
			},
			err: ErrInvalidTransport,
		},
		{
			name: "Transport in wrong case",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				Transport:             "Wi-Fi",
				SchemaVersion:         1,
			},
			err: ErrInvalidTransport,
		},
		{
			name: "SpecificationVersion is empty",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				SoftwareVersionString: testconstants.TestDate,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
			err: validator.ErrRequiredFieldMissing,
		},
		{
			name: "schemaVersion != 0",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: testconstants.SoftwareVersionString,
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       testconstants.SoftwareVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         5,
			},
			err: validator.ErrFieldEqualBoundViolated,
		},
		{
			name: "parentChild unsupported value",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: testconstants.SoftwareVersionString,
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       testconstants.SoftwareVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				ParentChild:           "parent/child",
				SchemaVersion:         1,
			},
			err: ErrInvalidPFCCertificationRoute,
		},
		{
			name: "parentChild wrong case",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: testconstants.SoftwareVersionString,
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       testconstants.SoftwareVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				ParentChild:           "Parent",
				SchemaVersion:         1,
			},
			err: ErrInvalidPFCCertificationRoute,
		},
		{
			name: "familyID contains hyphen",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: testconstants.SoftwareVersionString,
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       testconstants.SoftwareVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				FamilyId:              "FAM-123",
				SchemaVersion:         1,
			},
			err: ErrInvalidFamilyID,
		},
		{
			name: "familyID contains space",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: testconstants.SoftwareVersionString,
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       testconstants.SoftwareVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				FamilyId:              "FAM 123",
				SchemaVersion:         1,
			},
			err: ErrInvalidFamilyID,
		},
		{
			name: "certificationRoute wrong case",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: testconstants.SoftwareVersionString,
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       testconstants.SoftwareVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				CertificationRoute:    "FullTested",
				SchemaVersion:         1,
			},
			err: ErrInvalidCertificationRoute,
		},
		{
			name: "certificationRoute invalid value",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: testconstants.SoftwareVersionString,
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       testconstants.SoftwareVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				CertificationRoute:    "unknown-route",
				SchemaVersion:         1,
			},
			err: ErrInvalidCertificationRoute,
		},
	}

	positiveTests := []struct {
		name string
		msg  MsgProvisionModel
	}{
		{
			name: "valid provision model msg",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: testconstants.SoftwareVersionString,
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       testconstants.SoftwareVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
		},
		{
			name: "software version = 0",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: testconstants.SoftwareVersionString,
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
		},
		{
			name: "cd version number = 0",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: testconstants.SoftwareVersionString,
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       1,
				CDVersionNumber:       0,
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
		},
		{
			name: "certification type is zigbee",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: testconstants.SoftwareVersionString,
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     "zigbee",
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       testconstants.SoftwareVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
		},
		{
			name: "certification type is matter",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: testconstants.SoftwareVersionString,
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     "matter",
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       testconstants.SoftwareVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
		},
		{
			name: "minimal pid, vid values",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
		},
		{
			name: "max pid, vid values",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   65535,
				Vid:                   65535,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
		},
		{
			name: "ProgramTypeVersion >= 0 && ProgramTypeVersion <= 64",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				ProgramType:           EndProductProgramType,
				ProgramTypeVersion:    testconstants.ProgramTypeVersion,
				SchemaVersion:         1,
			},
		},
		{
			name: "CDCertificateId == 19",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				SchemaVersion:         1,
			},
		},
		{
			name: "FamilyId >= 0 && FamilyId <= 64",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				FamilyId:              testconstants.FamilyID,
				SchemaVersion:         1,
			},
		},
		{
			name: "SupportedClusters single value",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				SupportedClusters:     "0x0003",
				SchemaVersion:         1,
			},
		},
		{
			name: "SupportedClusters multiple comma-separated",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				SupportedClusters:     "0x0003,0x0004,0x0006,0x0008,0x0062,0x0300",
				SchemaVersion:         1,
			},
		},
		{
			name: "SupportedClusters short forms accepted",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				SupportedClusters:     "0x3,0x03,0x003,0x0003",
				SchemaVersion:         1,
			},
		},
		{
			name: "SupportedClusters mixed case hex",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				SupportedClusters:     "0xABCD,0x00fe",
				SchemaVersion:         1,
			},
		},
		{
			name: "SupportedClusters empty allowed",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				SupportedClusters:     "",
				SchemaVersion:         1,
			},
		},
		{
			name: "CompliancePlatformUsed >= 0 && CompliancePlatformUsed <= 64",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				CompliantPlatformUsed: testconstants.CompliantPlatformUsed,
				SchemaVersion:         1,
			},
		},
		{
			name: "CompliancePlatformVersion >= 0 && CompliancePlatformVersion <= 64",
			msg: MsgProvisionModel{
				Signer:                   sample.AccAddress(),
				SoftwareVersionString:    "1",
				Pid:                      1,
				Vid:                      1,
				ProvisionalDate:          testconstants.CertificationDate,
				CertificationType:        testconstants.CertificationType,
				SpecificationVersion:     testconstants.SpecificationVersion,
				SoftwareVersion:          0,
				CDVersionNumber:          uint32(testconstants.CdVersionNumber),
				CDCertificateId:          testconstants.CDCertificateID,
				CompliantPlatformVersion: testconstants.CompliantPlatformVersion,
				SchemaVersion:            1,
			},
		},
		{
			name: "OSVersion >= 0 && OSVersion <= 64",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				OSVersion:             testconstants.OSVersion,
				SchemaVersion:         1,
			},
		},
		{
			name: "CertificationRoute >= 0 && CertificationRoute <= 64",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				CertificationRoute:    testconstants.CertificationRoute,
				SchemaVersion:         1,
			},
		},
		{
			name: "supported CertificationRoute = rapid-recert",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				SoftwareVersionString: testconstants.TestDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				Reason:                testconstants.Reason,
				CDCertificateId:       testconstants.CDCertificateID,
				CertificationRoute:    CertificationRouteRapidRecert,
				SchemaVersion:         1,
			},
		},
		{
			name: "programType endProduct",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				ProgramType:           EndProductProgramType,
				ProgramTypeVersion:    testconstants.ProgramTypeVersion,
				SchemaVersion:         1,
			},
		},
		{
			name: "programType softwareComponent",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				ProgramType:           SoftwareComponentProgramType,
				ProgramTypeVersion:    testconstants.ProgramTypeVersion,
				SchemaVersion:         1,
			},
		},
		{
			name: "programType compliantPlatform",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				ProgramType:           CompliantPlatformProgramType,
				ProgramTypeVersion:    testconstants.ProgramTypeVersion,
				SchemaVersion:         1,
			},
		},
		{
			name: "programType empty allowed",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				ProgramType:           "",
				SchemaVersion:         1,
			},
		},
		{
			name: "Transport single supported value",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				Transport:             TransportThread,
				SchemaVersion:         1,
			},
		},
		{
			name: "Transport multiple supported values comma-separated",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				Transport:             "wi-fi,ethernet,bluetooth",
				SchemaVersion:         1,
			},
		},
		{
			name: "Transport with all supported values",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				Transport:             "thread,wi-fi,ethernet,bluetooth,nfc",
				SchemaVersion:         1,
			},
		},
		{
			name: "Transport empty is allowed",
			msg: MsgProvisionModel{
				Signer:                sample.AccAddress(),
				SoftwareVersionString: "1",
				Pid:                   1,
				Vid:                   1,
				ProvisionalDate:       testconstants.CertificationDate,
				CertificationType:     testconstants.CertificationType,
				SpecificationVersion:  testconstants.SpecificationVersion,
				SoftwareVersion:       0,
				CDVersionNumber:       uint32(testconstants.CdVersionNumber),
				CDCertificateId:       testconstants.CDCertificateID,
				Transport:             "",
				SchemaVersion:         1,
			},
		},
	}

	for _, tt := range negativeTests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.msg.ValidateBasic()
			require.Error(t, err)
			require.ErrorIs(t, err, tt.err)
		})
	}

	for _, tt := range positiveTests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.msg.ValidateBasic()
			require.NoError(t, err)
		})
	}
}
