package types

import (
	"testing"

	tmrand "github.com/cometbft/cometbft/libs/rand"
	sdkerrors "github.com/cosmos/cosmos-sdk/types/errors"
	"github.com/stretchr/testify/require"
	testconstants "github.com/zigbee-alliance/distributed-compliance-ledger/integration_tests/constants"
	"github.com/zigbee-alliance/distributed-compliance-ledger/testutil/sample"
	"github.com/zigbee-alliance/distributed-compliance-ledger/utils/validator"
)

func TestMsgUpdateComplianceInfo_ValidateBasic(t *testing.T) {
	tests := []struct {
		name string
		msg  MsgUpdateComplianceInfo
		err  error
	}{
		{
			name: "invalid address",
			msg: MsgUpdateComplianceInfo{
				Creator: "invalid_address",
			},
			err: sdkerrors.ErrInvalidAddress,
		},
		{
			name: "date is not RFC3339",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Pid:                  1,
				Vid:                  1,
				Date:                 "2020-01-01",
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				CDCertificateId:      testconstants.CDCertificateID,
			},
			err: ErrInvalidTestDateFormat,
		},
		{
			name: "invalid certification type",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Pid:                  1,
				Vid:                  1,
				Date:                 testconstants.CertificationDate,
				CertificationType:    "invalid type",
				SpecificationVersion: testconstants.SpecificationVersion,
				CDVersionNumber:      "312",
				Reason:               testconstants.Reason,
				CDCertificateId:      testconstants.CDCertificateID,
			},
			err: ErrInvalidCertificationType,
		},
		{
			name: "parent/child unsupported value",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				ParentChild:          "parent/child",
			},
			err: ErrInvalidPFCCertificationRoute,
		},
		{
			name: "parent/child wrong case",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				ParentChild:          "Parent",
			},
			err: ErrInvalidPFCCertificationRoute,
		},
		{
			name: "certificationRoute > 64",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Pid:                  1,
				Vid:                  1,
				Date:                 testconstants.CertificationDate,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				CDVersionNumber:      "312",
				Reason:               testconstants.Reason,
				CertificationRoute:   tmrand.Str(65),
			},
			err: validator.ErrFieldMaxLengthExceeded,
		},
		{
			name: "update compliance info message with all optional fields not set",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
			},
		},
		{
			name: "update compliance info message with all optional fields set",
			msg: MsgUpdateComplianceInfo{
				Creator:                            sample.AccAddress(),
				Vid:                                1,
				Pid:                                1,
				CertificationType:                  testconstants.CertificationType,
				SoftwareVersion:                    testconstants.SoftwareVersion,
				Reason:                             testconstants.Reason,
				CDVersionNumber:                    "312",
				CDCertificateId:                    testconstants.CDCertificateID,
				Date:                               testconstants.CertificationDate,
				ParentChild:                        "parent",
				CertificationRoute:                 testconstants.CertificationRoute,
				ProgramType:                        testconstants.ProgramType,
				ProgramTypeVersion:                 testconstants.ProgramTypeVersion,
				CompliantPlatformUsed:              testconstants.CompliantPlatformUsed,
				CompliantPlatformVersion:           testconstants.CompliantPlatformVersion,
				Transport:                          testconstants.Transport,
				FamilyId:                           testconstants.FamilyID,
				SupportedClusters:                  testconstants.SupportedClusters,
				OSVersion:                          testconstants.OSVersion,
				CertificationIdOfSoftwareComponent: testconstants.CertificationIDOfSoftwareComponent,
				SpecificationVersion:               testconstants.SpecificationVersion,
			},
		},
		{
			name: "valid update compliance info message",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
			},
		},
		{
			name: "certification type is zigbee",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Pid:                  1,
				Vid:                  1,
				Date:                 testconstants.CertificationDate,
				CertificationType:    "zigbee",
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				CDVersionNumber:      "312",
				CDCertificateId:      testconstants.CDCertificateID,
			},
		},
		{
			name: "certification type is matter",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Pid:                  1,
				Vid:                  1,
				Date:                 testconstants.CertificationDate,
				CertificationType:    "matter",
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				CDVersionNumber:      "312",
				CDCertificateId:      testconstants.CDCertificateID,
			},
		},
		{
			name: "cdVersionNumber > 65535",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "65536",
			},
			err: validator.ErrFieldUpperBoundViolated,
		},

		{
			name: "cdVersionNumber < 0",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "-1",
			},
			err: ErrInvalidUint32ForCdVersionNumber,
		},
		{
			name: "cDCertificateId > 19",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				CDCertificateId:      tmrand.Str(20),
			},
			err: validator.ErrFieldMaxLengthExceeded,
		},
		{
			name: "cDCertificateId < 19",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				CDCertificateId:      tmrand.Str(18),
			},
			err: validator.ErrFieldEqualBoundViolated,
		},
		{
			name: "non-integer cdVersionNumber",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "0.1402",
			},
			err: ErrInvalidUint32ForCdVersionNumber,
		},
		{
			name: "schemaVersion != 0",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Pid:                  1,
				Vid:                  1,
				Date:                 testconstants.CertificationDate,
				CertificationType:    "matter",
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				CDVersionNumber:      "312",
				CDCertificateId:      testconstants.CDCertificateID,
				SchemaVersion:        5,
			},
			err: validator.ErrFieldEqualBoundViolated,
		},
		{
			name: "Transport > 64",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				Transport:            tmrand.Str(65),
			},
			err: validator.ErrFieldMaxLengthExceeded,
		},
		{
			name: "Transport unsupported value",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				Transport:            "lora",
			},
			err: ErrInvalidTransport,
		},
		{
			name: "Transport mixes valid and unsupported value",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				Transport:            "wi-fi,lora",
			},
			err: ErrInvalidTransport,
		},
		{
			name: "Transport with whitespace after comma",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				Transport:            "wi-fi, ethernet",
			},
			err: ErrInvalidTransport,
		},
		{
			name: "Transport contains duplicate",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				Transport:            "wi-fi,wi-fi",
			},
			err: ErrInvalidTransport,
		},
		{
			name: "Transport with leading comma",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				Transport:            ",wi-fi",
			},
			err: ErrInvalidTransport,
		},
		{
			name: "Transport with trailing comma",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				Transport:            "wi-fi,",
			},
			err: ErrInvalidTransport,
		},
		{
			name: "Transport with empty entry between",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				Transport:            "wi-fi,,ethernet",
			},
			err: ErrInvalidTransport,
		},
		{
			name: "Transport in wrong case",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				Transport:            "Wi-Fi",
			},
			err: ErrInvalidTransport,
		},
		{
			name: "Transport single supported value",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				Transport:            TransportThread,
			},
		},
		{
			name: "Transport multiple supported values comma-separated",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				Transport:            "wi-fi,ethernet,bluetooth",
			},
		},
		{
			name: "Transport with all supported values",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				Transport:            "thread,wi-fi,ethernet,bluetooth,nfc",
			},
		},
		{
			name: "Transport empty is allowed",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				Transport:            "",
			},
		},
		{
			name: "SupportedClusters not hex",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				SupportedClusters:    "Some Supported Clusters",
			},
			err: ErrInvalidSupportedClusters,
		},
		{
			name: "SupportedClusters missing 0x prefix",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				SupportedClusters:    "0003,0004",
			},
			err: ErrInvalidSupportedClusters,
		},
		{
			name: "SupportedClusters more than 4 hex digits",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				SupportedClusters:    "0x00003",
			},
			err: ErrInvalidSupportedClusters,
		},
		{
			name: "SupportedClusters mixes valid and invalid entry",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				SupportedClusters:    "0x0003,zzz",
			},
			err: ErrInvalidSupportedClusters,
		},
		{
			name: "SupportedClusters with whitespace after comma",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				SupportedClusters:    "0x0003, 0x0004",
			},
			err: ErrInvalidSupportedClusters,
		},
		{
			name: "SupportedClusters contains duplicate",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				SupportedClusters:    "0x0003,0x0003",
			},
			err: ErrInvalidSupportedClusters,
		},
		{
			name: "SupportedClusters case-insensitive duplicate",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				SupportedClusters:    "0x000A,0x000a",
			},
			err: ErrInvalidSupportedClusters,
		},
		{
			name: "SupportedClusters with trailing comma",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				SupportedClusters:    "0x0003,",
			},
			err: ErrInvalidSupportedClusters,
		},
		{
			name: "SupportedClusters single value",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				SupportedClusters:    "0x0003",
			},
		},
		{
			name: "SupportedClusters multiple comma-separated",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				SupportedClusters:    "0x0003,0x0004,0x0006,0x0008,0x0062,0x0300",
			},
		},
		{
			name: "SupportedClusters short forms accepted",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				SupportedClusters:    "0x3,0x03,0x003,0x0003",
			},
		},
		{
			name: "SupportedClusters mixed case hex",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				SupportedClusters:    "0xABCD,0x00fe",
			},
		},
		{
			name: "SupportedClusters empty allowed",
			msg: MsgUpdateComplianceInfo{
				Creator:              sample.AccAddress(),
				Vid:                  1,
				Pid:                  1,
				CertificationType:    testconstants.CertificationType,
				SpecificationVersion: testconstants.SpecificationVersion,
				SoftwareVersion:      testconstants.SoftwareVersion,
				Reason:               testconstants.Reason,
				CDVersionNumber:      "312",
				SupportedClusters:    "",
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.msg.ValidateBasic()
			if tt.err != nil {
				require.ErrorIs(t, err, tt.err)

				return
			}
			require.NoError(t, err)
		})
	}
}
