---
# Copyright 2022 Samsung Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

dependency:
  name: galaxy
  options:
    requirements-file: ../../../galaxy-requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint -c ../../../../.yaml-lint.yml .
platforms:
  - name: node0
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - validators
  - name: node1
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - private_sentries
  - name: node2
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - observers
  - name: node3
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - public_sentries
  - name: node4
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - seeds
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../../../../inventory/group_vars
    group_vars:
      all:
        chain_id: test-net
verifier:
  name: testinfra
  lint:
    name: flake8
