# Copyright 2020 DSR Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# Builds dcld application for further use on nodes in DCL pool in docker.
# The resulting image is used only for getting the build artifact from
# a container based on it. Containers based on this image are never run.
################################################################################
FROM ubuntu:20.04 AS builder

ARG GO_VERSION
ENV GO_VERSION=1.20

RUN apt-get update
RUN apt-get install -y wget git gcc make

RUN wget -P /tmp "https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz"

RUN tar -C /usr/local -xzf "/tmp/go${GO_VERSION}.linux-amd64.tar.gz"
RUN rm "/tmp/go${GO_VERSION}.linux-amd64.tar.gz"

ENV GOPATH=/go
ENV PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"

WORKDIR /go/src
RUN git clone --depth 1 --single-branch --branch master "https://github.com/zigbee-alliance/distributed-compliance-ledger.git"
WORKDIR /go/src/distributed-compliance-ledger
COPY integration_tests/upgrade/test-upgrade.patch ./integration_tests/upgrade/test-upgrade.patch
RUN DCL_VERSION=$(git rev-parse --short HEAD)
RUN sed -i "s/TESTUPGRADE/$DCL_VERSION/" ./integration_tests/upgrade/test-upgrade.patch
RUN git apply ./integration_tests/upgrade/test-upgrade.patch
RUN LEDGER_ENABLED=false make
