# Copyright 2020 DSR Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# Builds the upgraded dcld application for upgrade procedure test needs.
# The resulting image is used only for getting the build artifact from
# a container based on it. Containers based on this image are never run.
################################################################################
FROM dcld-build

WORKDIR /go/src/dc-ledger

RUN cat ./app/app.go | tr '\n' '\r' | sed -e 's/'\
'	return app\r'\
'/'\
'	app.UpgradeKeeper.SetUpgradeHandler(\r'\
'		"v0.13.0-pre",\r'\
'		func(ctx sdk.Context, plan upgradetypes.Plan, fromVM module.VersionMap) (module.VersionMap, error) {\r'\
'			return make(module.VersionMap), nil\r'\
'		},\r'\
'	)\r'\
'\r'\
'	return app\r'\
'/' | tr '\r' '\n' | tee ./app/app.go

ARG DCL_VERSION
ARG DCL_COMMIT
RUN LEDGER_ENABLED=false make
