---
# Copyright 2022
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "2"

linters:
  default: all
  disable:
    - gochecknoinits
    - gochecknoglobals
    - mnd
    - dupl
    - varnamelen
    - tagliatelle
    - wrapcheck
    - testpackage
    - paralleltest
    - ireturn
    - err113
    - wsl
    - wsl_v5
    - forcetypeassert
    - exhaustive
    - godoclint
    - modernize
    - prealloc
    - noinlineerr
    - funcorder
    - recvcheck
    - intrange
    - copyloopvar
    - errname
    - lll
    - gosec
    - funlen
    - cyclop
    - forbidigo
    - gocognit
    - godox
    - gomoddirectives
    - containedctx
    - maintidx
    - nonamedreturns
    - exhaustruct
    - depguard
    - godot
    - inamedparam
    - goconst
    - perfsprint
    - unparam
    - revive
    - errcheck
    - predeclared
  settings:
    staticcheck:
      checks:
        - all
        - -QF*
        - -ST*
    govet:
      disable:
        - inline
  exclusions:
    rules:
      - path: _test\.go$
        linters:
          - goconst
          - staticcheck
          - testifylint
          - perfsprint
          - dupword
      - path: helpers\.go$
        linters:
          - goconst
          - staticcheck
          - testifylint
          - perfsprint
          - dupword
