---
# Copyright 2022
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

linters:
  enable-all: true
  disable:
    - golint  # The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive.
    - gochecknoinits
    - gochecknoglobals
    - gomnd
    - dupl
    - varnamelen
    - tagliatelle
    - wrapcheck
    - testpackage
    - paralleltest
    - ireturn
    - goerr113
    - exhaustivestruct
    - wsl
    - forcetypeassert
    - exhaustive
    - scopelint  # The linter 'scopelint' is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner.  Replaced by exportloopref.
    - lll
    - interfacer  # The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.
    - gosec
    - funlen
    - cyclop
    - forbidigo
    - gocognit
    - godox
    - gomoddirectives
    - maligned  # The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment'.
    - gci
    - containedctx
    - maintidx
    - execinquery
    - nonamedreturns
    - exhaustruct
    - gofumpt
