// Copyright 2020 DSR Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package types

// SchemaVersioned is implemented by every state object that carries a
// schemaVersion field. GetSchemaVersion is generated by gogoproto; the other
// two methods are implemented next to the message type (see e.g.
// x/compliance/types/schema_versions.go) and form the single source of truth
// for the type's current on-chain schema version.
type SchemaVersioned interface {
	GetSchemaVersion() uint32
	CurrentSchemaVersion() uint32
	SetSchemaVersion(v uint32)
}

// SchemaVersionGuard reports whether v should be stamped with its current
// schema version. Provide false to skip the write. Compose multiple guards by
// passing them all to SetCurrentSchemaVersion — they are evaluated in order
// and short-circuit on the first false.
type SchemaVersionGuard bool

// SetCurrentSchemaVersion writes the type's current schema version onto v,
// provided every guard accepts it. With no guards, it always sets it to the current version.
//
// See `x/compliance/types/schema_versions.go:21` for the per-type constants
// this helper writes.
func SetCurrentSchemaVersion(v SchemaVersioned, guards ...SchemaVersionGuard) {
	for _, guard := range guards {
		if !guard {
			return
		}
	}

	v.SetSchemaVersion(v.CurrentSchemaVersion())
}
