#!/bin/bash
# Copyright 2022 DSR Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu
set -o pipefail

PORT="${1:-26656}"

function usage {
  echo "\
Usage: $0 [port]

Runs echo server on a given port
"
}

if [[ ("${1-}" == "-h" || "${1:-}" == "--help") ]]; then
    usage
    exit 0
fi

if [[ -z "$(which ncat)" ]]; then
    echo '"ncat" not found. installing...'
    sudo apt update -y && sudo apt install ncat -y
fi

if [[ -z "$(sudo lsof -t -i:"$PORT")" ]]; then
    echo "running ncat echo server on port $PORT"
    ncat -l "$PORT" --keep-open --exec "/bin/cat" &
    exit 0
else 
    echo "port $PORT is busy"
    exit 1
fi