package cli

const (
	// Flags for Model.
	FlagVid                                        = "vid"
	FlagPid                                        = "pid"
	FlagDeviceTypeID                               = "deviceTypeID"
	FlagProductName                                = "productName"
	FlagProductNameShortcut                        = "n"
	FlagProductLabel                               = "productLabel"
	FlagProductLabelShortcut                       = "d"
	FlagPartNumber                                 = "partNumber"
	FlagDiscoveryCapabilitiesBitmask               = "discoveryCapabilitiesBitmask"
	FlagCommissioningCustomFlow                    = "commissioningCustomFlow"
	FlagCommissioningCustomFlowURL                 = "commissioningCustomFlowURL"
	FlagCommissioningModeInitialStepsHint          = "commissioningModeInitialStepsHint"
	FlagCommissioningModeInitialStepsInstruction   = "commissioningModeInitialStepsInstruction"
	FlagCommissioningModeSecondaryStepsHint        = "commissioningModeSecondaryStepsHint"
	FlagCommissioningModeSecondaryStepsInstruction = "commissioningModeSecondaryStepsInstruction"
	FlagIcdUserActiveModeTriggerHint               = "icdUserActiveModeTriggerHint"
	FlagIcdUserActiveModeTriggerInstruction        = "icdUserActiveModeTriggerInstruction"
	FlagUserManualURL                              = "userManualURL"
	FlagSupportURL                                 = "supportURL"
	FlagProductURL                                 = "productURL"
	FlagLsfURL                                     = "lsfURL"
	FlagLsfRevision                                = "lsfRevision"
	FlagEnhancedSetupFlowOptions                   = "enhancedSetupFlowOptions"
	FlagEnhancedSetupFlowTCURL                     = "enhancedSetupFlowTCUrl"
	FlagEnhancedSetupFlowTCRevision                = "enhancedSetupFlowTCRevision"
	FlagEnhancedSetupFlowTCDigest                  = "enhancedSetupFlowTCDigest"
	FlagEnhancedSetupFlowTCFileSize                = "enhancedSetupFlowTCFileSize"
	FlagMaintenanceURL                             = "maintenanceUrl"
	FlagCommissioningFallbackURL                   = "commissioningFallbackUrl"
	// Flags for ModelVersion.
	FlagSoftwareVersion              = "softwareVersion"
	FlagSoftwareVersionShortcut      = "v"
	FlagSoftwareVersionString        = "softwareVersionString"
	FlagCdVersionNumber              = "cdVersionNumber"
	FlagFirmwareInformation          = "firmwareInformation"
	FlagSoftwareVersionValid         = "softwareVersionValid"
	FlagOtaURL                       = "otaURL"
	FlagOtaFileSize                  = "otaFileSize"
	FlagOtaChecksum                  = "otaChecksum"
	FlagOtaChecksumType              = "otaChecksumType"
	FlagMinApplicableSoftwareVersion = "minApplicableSoftwareVersion"
	FlagMaxApplicableSoftwareVersion = "maxApplicableSoftwareVersion"
	FlagReleaseNotesURL              = "releaseNotesURL"
	FlagSpecificationVersion         = "specificationVersion"
)
