package cli

const (
	// Flags for Model.
	FlagVid                                        = "vid"
	FlagPid                                        = "pid"
	FlagDeviceTypeID                               = "deviceTypeID"
	FlagProductName                                = "productName"
	FlagProductNameShortcut                        = "n"
	FlagProductLabel                               = "productLabel"
	FlagProductLabelShortcut                       = "d"
	FlagPartNumber                                 = "partNumber"
	FlagCommissioningCustomFlow                    = "commissioningCustomFlow"
	FlagCommissioningCustomFlowURL                 = "commissioningCustomFlowURL"
	FlagCommissioningModeInitialStepsHint          = "commissioningModeInitialStepsHint"
	FlagCommissioningModeInitialStepsInstruction   = "commissioningModeInitialStepsInstruction"
	FlagCommissioningModeSecondaryStepsHint        = "commissioningModeSecondaryStepsHint"
	FlagCommissioningModeSecondaryStepsInstruction = "commissioningModeSecondaryStepsInstruction"
	FlagManagedACLExtensionRequestFlowURL          = "managedAclExtensionRequestFlowUrl"
	FlagUserManualURL                              = "userManualURL"
	FlagSupportURL                                 = "supportURL"
	FlagProductURL                                 = "productURL"
	FlagLsfURL                                     = "lsfURL"
	FlagLsfRevision                                = "lsfRevision"

	// Flags for ModelVersion.
	FlagSoftwareVersion              = "softwareVersion"
	FlagSoftwareVersionShortcut      = "v"
	FlagSoftwareVersionString        = "softwareVersionString"
	FlagCdVersionNumber              = "cdVersionNumber"
	FlagFirmwareInformation          = "firmwareInformation"
	FlagSoftwareVersionValid         = "softwareVersionValid"
	FlagOtaURL                       = "otaURL"
	FlagOtaFileSize                  = "otaFileSize"
	FlagOtaChecksum                  = "otaChecksum"
	FlagOtaChecksumType              = "otaChecksumType"
	FlagMinApplicableSoftwareVersion = "minApplicableSoftwareVersion"
	FlagMaxApplicableSoftwareVersion = "maxApplicableSoftwareVersion"
	FlagReleaseNotesURL              = "releaseNotesURL"
)
