// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dclauth/pending_account.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PendingAccount struct {
	Address   string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Approvals []string `protobuf:"bytes,2,rep,name=approvals,proto3" json:"approvals,omitempty"`
}

func (m *PendingAccount) Reset()         { *m = PendingAccount{} }
func (m *PendingAccount) String() string { return proto.CompactTextString(m) }
func (*PendingAccount) ProtoMessage()    {}
func (*PendingAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e7d87157315e5f1, []int{0}
}
func (m *PendingAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PendingAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PendingAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PendingAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingAccount.Merge(m, src)
}
func (m *PendingAccount) XXX_Size() int {
	return m.Size()
}
func (m *PendingAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingAccount.DiscardUnknown(m)
}

var xxx_messageInfo_PendingAccount proto.InternalMessageInfo

func (m *PendingAccount) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PendingAccount) GetApprovals() []string {
	if m != nil {
		return m.Approvals
	}
	return nil
}

func init() {
	proto.RegisterType((*PendingAccount)(nil), "zigbeealliance.distributedcomplianceledger.dclauth.PendingAccount")
}

func init() { proto.RegisterFile("dclauth/pending_account.proto", fileDescriptor_8e7d87157315e5f1) }

var fileDescriptor_8e7d87157315e5f1 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcf, 0xbb, 0x4a, 0x04, 0x31,
	0x14, 0xc6, 0xf1, 0x89, 0x82, 0x32, 0x29, 0x2c, 0xa6, 0x9a, 0x42, 0xc3, 0x62, 0xb5, 0xcd, 0x24,
	0xa0, 0x4f, 0xa0, 0xd5, 0x96, 0xb2, 0xa5, 0x8d, 0xe4, 0x72, 0xc8, 0x06, 0xb2, 0x49, 0xc8, 0x45,
	0xd4, 0xa7, 0xf0, 0xb1, 0x2c, 0xa7, 0xb4, 0x94, 0x99, 0x17, 0x11, 0x8c, 0xc3, 0x6c, 0x79, 0x4e,
	0xf1, 0xe7, 0xf7, 0xe1, 0x1b, 0x25, 0x2d, 0x2f, 0xf9, 0xc0, 0x02, 0x38, 0x65, 0x9c, 0x7e, 0xe1,
	0x52, 0xfa, 0xe2, 0x32, 0x0d, 0xd1, 0x67, 0xdf, 0xdd, 0x7d, 0x18, 0x2d, 0x00, 0xb8, 0xb5, 0x86,
	0x3b, 0x09, 0x54, 0x99, 0x94, 0xa3, 0x11, 0x25, 0x83, 0x92, 0xfe, 0x18, 0xea, 0xd7, 0x82, 0xd2,
	0x10, 0xe9, 0x7f, 0xe9, 0x76, 0x87, 0xaf, 0x9e, 0x6a, 0xec, 0xa1, 0xb6, 0xba, 0x1e, 0x5f, 0x72,
	0xa5, 0x22, 0xa4, 0xd4, 0xa3, 0x0d, 0xda, 0xb6, 0xfb, 0xe5, 0xec, 0xae, 0x71, 0xcb, 0x43, 0x88,
	0xfe, 0x95, 0xdb, 0xd4, 0x9f, 0x6d, 0xce, 0xb7, 0xed, 0x7e, 0x7d, 0x3c, 0x8a, 0xaf, 0x89, 0xa0,
	0x71, 0x22, 0xe8, 0x67, 0x22, 0xe8, 0x73, 0x26, 0xcd, 0x38, 0x93, 0xe6, 0x7b, 0x26, 0xcd, 0xf3,
	0x4e, 0x9b, 0x7c, 0x28, 0x82, 0x4a, 0x7f, 0x64, 0x95, 0x38, 0x2c, 0x46, 0x76, 0x62, 0x1c, 0x56,
	0xe4, 0x50, 0x95, 0xec, 0x8d, 0x2d, 0x8b, 0xf3, 0x7b, 0x80, 0x24, 0x2e, 0xfe, 0x86, 0xde, 0xff,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x88, 0x9e, 0xab, 0x47, 0x09, 0x01, 0x00, 0x00,
}

func (m *PendingAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PendingAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PendingAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Approvals) > 0 {
		for iNdEx := len(m.Approvals) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Approvals[iNdEx])
			copy(dAtA[i:], m.Approvals[iNdEx])
			i = encodeVarintPendingAccount(dAtA, i, uint64(len(m.Approvals[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintPendingAccount(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPendingAccount(dAtA []byte, offset int, v uint64) int {
	offset -= sovPendingAccount(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PendingAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovPendingAccount(uint64(l))
	}
	if len(m.Approvals) > 0 {
		for _, s := range m.Approvals {
			l = len(s)
			n += 1 + l + sovPendingAccount(uint64(l))
		}
	}
	return n
}

func sovPendingAccount(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPendingAccount(x uint64) (n int) {
	return sovPendingAccount(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PendingAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPendingAccount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PendingAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PendingAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPendingAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPendingAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPendingAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approvals", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPendingAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPendingAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPendingAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Approvals = append(m.Approvals, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPendingAccount(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPendingAccount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPendingAccount(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPendingAccount
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPendingAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPendingAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPendingAccount
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPendingAccount
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPendingAccount
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPendingAccount        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPendingAccount          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPendingAccount = fmt.Errorf("proto: unexpected end of group")
)
