// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: model/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetVendorProductsRequest struct {
	Vid int32 `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"`
}

func (m *QueryGetVendorProductsRequest) Reset()         { *m = QueryGetVendorProductsRequest{} }
func (m *QueryGetVendorProductsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetVendorProductsRequest) ProtoMessage()    {}
func (*QueryGetVendorProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed1e5616dfbc517, []int{0}
}
func (m *QueryGetVendorProductsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVendorProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVendorProductsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVendorProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVendorProductsRequest.Merge(m, src)
}
func (m *QueryGetVendorProductsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVendorProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVendorProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVendorProductsRequest proto.InternalMessageInfo

func (m *QueryGetVendorProductsRequest) GetVid() int32 {
	if m != nil {
		return m.Vid
	}
	return 0
}

type QueryGetVendorProductsResponse struct {
	VendorProducts VendorProducts `protobuf:"bytes,1,opt,name=vendorProducts,proto3" json:"vendorProducts"`
}

func (m *QueryGetVendorProductsResponse) Reset()         { *m = QueryGetVendorProductsResponse{} }
func (m *QueryGetVendorProductsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetVendorProductsResponse) ProtoMessage()    {}
func (*QueryGetVendorProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed1e5616dfbc517, []int{1}
}
func (m *QueryGetVendorProductsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVendorProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVendorProductsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVendorProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVendorProductsResponse.Merge(m, src)
}
func (m *QueryGetVendorProductsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVendorProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVendorProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVendorProductsResponse proto.InternalMessageInfo

func (m *QueryGetVendorProductsResponse) GetVendorProducts() VendorProducts {
	if m != nil {
		return m.VendorProducts
	}
	return VendorProducts{}
}

type QueryAllVendorProductsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllVendorProductsRequest) Reset()         { *m = QueryAllVendorProductsRequest{} }
func (m *QueryAllVendorProductsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllVendorProductsRequest) ProtoMessage()    {}
func (*QueryAllVendorProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed1e5616dfbc517, []int{2}
}
func (m *QueryAllVendorProductsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllVendorProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllVendorProductsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllVendorProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllVendorProductsRequest.Merge(m, src)
}
func (m *QueryAllVendorProductsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllVendorProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllVendorProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllVendorProductsRequest proto.InternalMessageInfo

func (m *QueryAllVendorProductsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllVendorProductsResponse struct {
	VendorProducts []VendorProducts    `protobuf:"bytes,1,rep,name=vendorProducts,proto3" json:"vendorProducts"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllVendorProductsResponse) Reset()         { *m = QueryAllVendorProductsResponse{} }
func (m *QueryAllVendorProductsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllVendorProductsResponse) ProtoMessage()    {}
func (*QueryAllVendorProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed1e5616dfbc517, []int{3}
}
func (m *QueryAllVendorProductsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllVendorProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllVendorProductsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllVendorProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllVendorProductsResponse.Merge(m, src)
}
func (m *QueryAllVendorProductsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllVendorProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllVendorProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllVendorProductsResponse proto.InternalMessageInfo

func (m *QueryAllVendorProductsResponse) GetVendorProducts() []VendorProducts {
	if m != nil {
		return m.VendorProducts
	}
	return nil
}

func (m *QueryAllVendorProductsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetModelRequest struct {
	Vid int32 `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"`
	Pid int32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (m *QueryGetModelRequest) Reset()         { *m = QueryGetModelRequest{} }
func (m *QueryGetModelRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetModelRequest) ProtoMessage()    {}
func (*QueryGetModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed1e5616dfbc517, []int{4}
}
func (m *QueryGetModelRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetModelRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetModelRequest.Merge(m, src)
}
func (m *QueryGetModelRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetModelRequest proto.InternalMessageInfo

func (m *QueryGetModelRequest) GetVid() int32 {
	if m != nil {
		return m.Vid
	}
	return 0
}

func (m *QueryGetModelRequest) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

type QueryGetModelResponse struct {
	Model Model `protobuf:"bytes,1,opt,name=model,proto3" json:"model"`
}

func (m *QueryGetModelResponse) Reset()         { *m = QueryGetModelResponse{} }
func (m *QueryGetModelResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetModelResponse) ProtoMessage()    {}
func (*QueryGetModelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed1e5616dfbc517, []int{5}
}
func (m *QueryGetModelResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetModelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetModelResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetModelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetModelResponse.Merge(m, src)
}
func (m *QueryGetModelResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetModelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetModelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetModelResponse proto.InternalMessageInfo

func (m *QueryGetModelResponse) GetModel() Model {
	if m != nil {
		return m.Model
	}
	return Model{}
}

type QueryAllModelRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllModelRequest) Reset()         { *m = QueryAllModelRequest{} }
func (m *QueryAllModelRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllModelRequest) ProtoMessage()    {}
func (*QueryAllModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed1e5616dfbc517, []int{6}
}
func (m *QueryAllModelRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllModelRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllModelRequest.Merge(m, src)
}
func (m *QueryAllModelRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllModelRequest proto.InternalMessageInfo

func (m *QueryAllModelRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllModelResponse struct {
	Model      []Model             `protobuf:"bytes,1,rep,name=model,proto3" json:"model"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllModelResponse) Reset()         { *m = QueryAllModelResponse{} }
func (m *QueryAllModelResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllModelResponse) ProtoMessage()    {}
func (*QueryAllModelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed1e5616dfbc517, []int{7}
}
func (m *QueryAllModelResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllModelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllModelResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllModelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllModelResponse.Merge(m, src)
}
func (m *QueryAllModelResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllModelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllModelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllModelResponse proto.InternalMessageInfo

func (m *QueryAllModelResponse) GetModel() []Model {
	if m != nil {
		return m.Model
	}
	return nil
}

func (m *QueryAllModelResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetModelVersionRequest struct {
	Vid             int32  `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"`
	Pid             int32  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	SoftwareVersion uint32 `protobuf:"varint,3,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
}

func (m *QueryGetModelVersionRequest) Reset()         { *m = QueryGetModelVersionRequest{} }
func (m *QueryGetModelVersionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetModelVersionRequest) ProtoMessage()    {}
func (*QueryGetModelVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed1e5616dfbc517, []int{8}
}
func (m *QueryGetModelVersionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetModelVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetModelVersionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetModelVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetModelVersionRequest.Merge(m, src)
}
func (m *QueryGetModelVersionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetModelVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetModelVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetModelVersionRequest proto.InternalMessageInfo

func (m *QueryGetModelVersionRequest) GetVid() int32 {
	if m != nil {
		return m.Vid
	}
	return 0
}

func (m *QueryGetModelVersionRequest) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *QueryGetModelVersionRequest) GetSoftwareVersion() uint32 {
	if m != nil {
		return m.SoftwareVersion
	}
	return 0
}

type QueryGetModelVersionResponse struct {
	ModelVersion ModelVersion `protobuf:"bytes,1,opt,name=modelVersion,proto3" json:"modelVersion"`
}

func (m *QueryGetModelVersionResponse) Reset()         { *m = QueryGetModelVersionResponse{} }
func (m *QueryGetModelVersionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetModelVersionResponse) ProtoMessage()    {}
func (*QueryGetModelVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed1e5616dfbc517, []int{9}
}
func (m *QueryGetModelVersionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetModelVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetModelVersionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetModelVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetModelVersionResponse.Merge(m, src)
}
func (m *QueryGetModelVersionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetModelVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetModelVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetModelVersionResponse proto.InternalMessageInfo

func (m *QueryGetModelVersionResponse) GetModelVersion() ModelVersion {
	if m != nil {
		return m.ModelVersion
	}
	return ModelVersion{}
}

type QueryAllModelVersionRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllModelVersionRequest) Reset()         { *m = QueryAllModelVersionRequest{} }
func (m *QueryAllModelVersionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllModelVersionRequest) ProtoMessage()    {}
func (*QueryAllModelVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed1e5616dfbc517, []int{10}
}
func (m *QueryAllModelVersionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllModelVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllModelVersionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllModelVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllModelVersionRequest.Merge(m, src)
}
func (m *QueryAllModelVersionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllModelVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllModelVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllModelVersionRequest proto.InternalMessageInfo

func (m *QueryAllModelVersionRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllModelVersionResponse struct {
	ModelVersion []ModelVersion      `protobuf:"bytes,1,rep,name=modelVersion,proto3" json:"modelVersion"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllModelVersionResponse) Reset()         { *m = QueryAllModelVersionResponse{} }
func (m *QueryAllModelVersionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllModelVersionResponse) ProtoMessage()    {}
func (*QueryAllModelVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed1e5616dfbc517, []int{11}
}
func (m *QueryAllModelVersionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllModelVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllModelVersionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllModelVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllModelVersionResponse.Merge(m, src)
}
func (m *QueryAllModelVersionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllModelVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllModelVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllModelVersionResponse proto.InternalMessageInfo

func (m *QueryAllModelVersionResponse) GetModelVersion() []ModelVersion {
	if m != nil {
		return m.ModelVersion
	}
	return nil
}

func (m *QueryAllModelVersionResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetModelVersionsRequest struct {
	Vid int32 `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"`
	Pid int32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (m *QueryGetModelVersionsRequest) Reset()         { *m = QueryGetModelVersionsRequest{} }
func (m *QueryGetModelVersionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetModelVersionsRequest) ProtoMessage()    {}
func (*QueryGetModelVersionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed1e5616dfbc517, []int{12}
}
func (m *QueryGetModelVersionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetModelVersionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetModelVersionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetModelVersionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetModelVersionsRequest.Merge(m, src)
}
func (m *QueryGetModelVersionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetModelVersionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetModelVersionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetModelVersionsRequest proto.InternalMessageInfo

func (m *QueryGetModelVersionsRequest) GetVid() int32 {
	if m != nil {
		return m.Vid
	}
	return 0
}

func (m *QueryGetModelVersionsRequest) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

type QueryGetModelVersionsResponse struct {
	ModelVersions ModelVersions `protobuf:"bytes,1,opt,name=modelVersions,proto3" json:"modelVersions"`
}

func (m *QueryGetModelVersionsResponse) Reset()         { *m = QueryGetModelVersionsResponse{} }
func (m *QueryGetModelVersionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetModelVersionsResponse) ProtoMessage()    {}
func (*QueryGetModelVersionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed1e5616dfbc517, []int{13}
}
func (m *QueryGetModelVersionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetModelVersionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetModelVersionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetModelVersionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetModelVersionsResponse.Merge(m, src)
}
func (m *QueryGetModelVersionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetModelVersionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetModelVersionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetModelVersionsResponse proto.InternalMessageInfo

func (m *QueryGetModelVersionsResponse) GetModelVersions() ModelVersions {
	if m != nil {
		return m.ModelVersions
	}
	return ModelVersions{}
}

type QueryAllModelVersionsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllModelVersionsRequest) Reset()         { *m = QueryAllModelVersionsRequest{} }
func (m *QueryAllModelVersionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllModelVersionsRequest) ProtoMessage()    {}
func (*QueryAllModelVersionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed1e5616dfbc517, []int{14}
}
func (m *QueryAllModelVersionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllModelVersionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllModelVersionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllModelVersionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllModelVersionsRequest.Merge(m, src)
}
func (m *QueryAllModelVersionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllModelVersionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllModelVersionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllModelVersionsRequest proto.InternalMessageInfo

func (m *QueryAllModelVersionsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllModelVersionsResponse struct {
	ModelVersions []ModelVersions     `protobuf:"bytes,1,rep,name=modelVersions,proto3" json:"modelVersions"`
	Pagination    *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllModelVersionsResponse) Reset()         { *m = QueryAllModelVersionsResponse{} }
func (m *QueryAllModelVersionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllModelVersionsResponse) ProtoMessage()    {}
func (*QueryAllModelVersionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed1e5616dfbc517, []int{15}
}
func (m *QueryAllModelVersionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllModelVersionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllModelVersionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllModelVersionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllModelVersionsResponse.Merge(m, src)
}
func (m *QueryAllModelVersionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllModelVersionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllModelVersionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllModelVersionsResponse proto.InternalMessageInfo

func (m *QueryAllModelVersionsResponse) GetModelVersions() []ModelVersions {
	if m != nil {
		return m.ModelVersions
	}
	return nil
}

func (m *QueryAllModelVersionsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetVendorProductsRequest)(nil), "zigbeealliance.distributedcomplianceledger.model.QueryGetVendorProductsRequest")
	proto.RegisterType((*QueryGetVendorProductsResponse)(nil), "zigbeealliance.distributedcomplianceledger.model.QueryGetVendorProductsResponse")
	proto.RegisterType((*QueryAllVendorProductsRequest)(nil), "zigbeealliance.distributedcomplianceledger.model.QueryAllVendorProductsRequest")
	proto.RegisterType((*QueryAllVendorProductsResponse)(nil), "zigbeealliance.distributedcomplianceledger.model.QueryAllVendorProductsResponse")
	proto.RegisterType((*QueryGetModelRequest)(nil), "zigbeealliance.distributedcomplianceledger.model.QueryGetModelRequest")
	proto.RegisterType((*QueryGetModelResponse)(nil), "zigbeealliance.distributedcomplianceledger.model.QueryGetModelResponse")
	proto.RegisterType((*QueryAllModelRequest)(nil), "zigbeealliance.distributedcomplianceledger.model.QueryAllModelRequest")
	proto.RegisterType((*QueryAllModelResponse)(nil), "zigbeealliance.distributedcomplianceledger.model.QueryAllModelResponse")
	proto.RegisterType((*QueryGetModelVersionRequest)(nil), "zigbeealliance.distributedcomplianceledger.model.QueryGetModelVersionRequest")
	proto.RegisterType((*QueryGetModelVersionResponse)(nil), "zigbeealliance.distributedcomplianceledger.model.QueryGetModelVersionResponse")
	proto.RegisterType((*QueryAllModelVersionRequest)(nil), "zigbeealliance.distributedcomplianceledger.model.QueryAllModelVersionRequest")
	proto.RegisterType((*QueryAllModelVersionResponse)(nil), "zigbeealliance.distributedcomplianceledger.model.QueryAllModelVersionResponse")
	proto.RegisterType((*QueryGetModelVersionsRequest)(nil), "zigbeealliance.distributedcomplianceledger.model.QueryGetModelVersionsRequest")
	proto.RegisterType((*QueryGetModelVersionsResponse)(nil), "zigbeealliance.distributedcomplianceledger.model.QueryGetModelVersionsResponse")
	proto.RegisterType((*QueryAllModelVersionsRequest)(nil), "zigbeealliance.distributedcomplianceledger.model.QueryAllModelVersionsRequest")
	proto.RegisterType((*QueryAllModelVersionsResponse)(nil), "zigbeealliance.distributedcomplianceledger.model.QueryAllModelVersionsResponse")
}

func init() { proto.RegisterFile("model/query.proto", fileDescriptor_7ed1e5616dfbc517) }

var fileDescriptor_7ed1e5616dfbc517 = []byte{
	// 885 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x98, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0xeb, 0x96, 0x22, 0x64, 0xf6, 0xd7, 0x1a, 0xd2, 0xe8, 0x46, 0x99, 0x72, 0x80, 0x81,
	0xb4, 0x84, 0x8d, 0x03, 0x68, 0x07, 0x58, 0xcb, 0xd4, 0x8d, 0x89, 0xb2, 0x52, 0xc4, 0x0e, 0x1c,
	0x18, 0x69, 0xe3, 0x65, 0x11, 0x69, 0x9c, 0x25, 0x69, 0x61, 0x4c, 0xbb, 0x4c, 0x42, 0x70, 0xe0,
	0x30, 0x09, 0x89, 0x6f, 0xc2, 0x77, 0xd8, 0x71, 0x08, 0x21, 0xc1, 0x01, 0x84, 0x36, 0xc4, 0x87,
	0xe0, 0x30, 0xa1, 0x38, 0x0e, 0x4d, 0xba, 0xb6, 0xd0, 0xc4, 0xbb, 0x54, 0x91, 0x5b, 0x3f, 0xef,
	0xfb, 0x7b, 0x1e, 0xc7, 0xb6, 0x0a, 0x87, 0x6b, 0x44, 0xc1, 0xba, 0xb4, 0x51, 0xc7, 0xd6, 0xa6,
	0x68, 0x5a, 0xc4, 0x21, 0xe8, 0xda, 0x4b, 0x4d, 0xad, 0x60, 0x2c, 0xeb, 0xba, 0x26, 0x1b, 0x55,
	0x2c, 0x2a, 0x9a, 0xed, 0x58, 0x5a, 0xa5, 0xee, 0x60, 0xa5, 0x4a, 0x6a, 0xa6, 0x37, 0xaa, 0x63,
	0x45, 0xc5, 0x96, 0x48, 0x67, 0x67, 0xc6, 0x55, 0x42, 0x54, 0x1d, 0x4b, 0xb2, 0xa9, 0x49, 0xb2,
	0x61, 0x10, 0x47, 0x76, 0x34, 0x62, 0xd8, 0x9e, 0x5e, 0xe6, 0x6a, 0x95, 0xd8, 0x35, 0x62, 0x4b,
	0x15, 0xd9, 0xc6, 0x5e, 0x21, 0xa9, 0x31, 0x5d, 0xc1, 0x8e, 0x3c, 0x2d, 0x99, 0xb2, 0xaa, 0x19,
	0xf4, 0xc7, 0xec, 0xb7, 0x63, 0x5e, 0x3b, 0x0d, 0x6c, 0x28, 0xc4, 0x5a, 0x35, 0x2d, 0xa2, 0xd4,
	0xab, 0x8e, 0x2f, 0xc4, 0x7a, 0xa5, 0x9f, 0x6c, 0xe8, 0x7c, 0x60, 0x68, 0xb5, 0x81, 0x2d, 0xbb,
	0x29, 0x95, 0x69, 0xf3, 0x95, 0xaf, 0x34, 0xa2, 0x12, 0x95, 0xd0, 0x47, 0xc9, 0x7d, 0xf2, 0x46,
	0x85, 0x69, 0x78, 0xe1, 0x81, 0xdb, 0xde, 0x02, 0x76, 0x56, 0x68, 0x03, 0x25, 0x56, 0xbf, 0x8c,
	0x37, 0xea, 0xd8, 0x76, 0xd0, 0x10, 0x4c, 0x35, 0x34, 0x65, 0x14, 0x4c, 0x80, 0xc9, 0x74, 0xd9,
	0x7d, 0x14, 0x76, 0x01, 0xcc, 0x76, 0x9a, 0x63, 0x9b, 0xc4, 0xb0, 0x31, 0x32, 0xe0, 0x40, 0x23,
	0xf4, 0x0d, 0x9d, 0x7f, 0x76, 0x66, 0x4e, 0xec, 0xd5, 0x67, 0x31, 0x5c, 0x21, 0x7f, 0x6a, 0xef,
	0xfb, 0xc5, 0x44, 0xb9, 0x45, 0x5d, 0x50, 0x19, 0x45, 0x4e, 0xd7, 0xdb, 0x53, 0x14, 0x20, 0x6c,
	0xfa, 0xce, 0x9a, 0xb9, 0x24, 0x7a, 0x21, 0x89, 0x6e, 0x48, 0xa2, 0xb7, 0x1a, 0x58, 0x48, 0x62,
	0x49, 0x56, 0x31, 0x9b, 0x5b, 0x0e, 0xcc, 0x14, 0xbe, 0xfa, 0xec, 0x6d, 0x2a, 0x75, 0x61, 0x4f,
	0x9d, 0x1c, 0x3b, 0x5a, 0x08, 0xa1, 0x25, 0x29, 0xda, 0xe5, 0x7f, 0xa2, 0x79, 0xcd, 0x86, 0xd8,
	0x66, 0xe1, 0x88, 0x1f, 0x6b, 0xd1, 0x2d, 0xdf, 0x71, 0x05, 0xb8, 0x23, 0xa6, 0xa6, 0xd0, 0x5a,
	0xe9, 0xb2, 0xfb, 0x28, 0xe8, 0xf0, 0x5c, 0xcb, 0x5c, 0xe6, 0xc6, 0x43, 0x98, 0xa6, 0x2c, 0xcc,
	0xf3, 0x1b, 0xbd, 0x9b, 0x40, 0xf5, 0x18, 0xbb, 0xa7, 0x25, 0x3c, 0x61, 0x9d, 0xe6, 0x74, 0x3d,
	0xd4, 0x29, 0xaf, 0x94, 0x3f, 0x00, 0x86, 0xd3, 0x2c, 0x70, 0x1c, 0x27, 0xc5, 0x0b, 0x87, 0x5f,
	0x82, 0x3a, 0x1c, 0x0b, 0xa5, 0xb0, 0xe2, 0xed, 0x00, 0x3d, 0x04, 0x89, 0xae, 0xc0, 0x21, 0x9b,
	0xac, 0x39, 0xcf, 0x65, 0x0b, 0xfb, 0x1b, 0xc8, 0x68, 0x6a, 0x02, 0x4c, 0xf6, 0x97, 0x07, 0xfd,
	0x71, 0xa6, 0x2a, 0xbc, 0x01, 0x70, 0xbc, 0x7d, 0x39, 0x66, 0xd6, 0x3a, 0xec, 0xab, 0x05, 0xc6,
	0x59, 0x20, 0xb7, 0x22, 0x7a, 0xc6, 0x54, 0x98, 0x75, 0x21, 0x65, 0x01, 0x33, 0x70, 0x3f, 0xaf,
	0x16, 0x70, 0x5e, 0xeb, 0xe2, 0xa3, 0x4f, 0x7c, 0xac, 0x4e, 0x47, 0xe2, 0xd4, 0xc9, 0x10, 0xf3,
	0x5b, 0x33, 0xf9, 0xf6, 0x21, 0xda, 0xbd, 0xbc, 0xfd, 0x6f, 0x41, 0xf3, 0x14, 0x69, 0x11, 0x61,
	0xc6, 0x3c, 0x83, 0xfd, 0xc1, 0xf6, 0xfd, 0xf3, 0xe0, 0x76, 0x3c, 0x67, 0xfc, 0x2d, 0x31, 0xac,
	0x2d, 0xac, 0xb5, 0x4f, 0x89, 0xfb, 0x61, 0xf0, 0x19, 0x34, 0x8f, 0x9d, 0xff, 0xc6, 0x4e, 0x9d,
	0x14, 0x36, 0xb7, 0x25, 0x31, 0x73, 0x34, 0x08, 0xd3, 0x94, 0x0b, 0xbd, 0x4a, 0xc2, 0x81, 0xf0,
	0x21, 0x84, 0x96, 0x7b, 0xef, 0xbd, 0xeb, 0x05, 0x23, 0x53, 0xe2, 0x27, 0xe8, 0xb1, 0x08, 0xa5,
	0x9d, 0x4f, 0x3f, 0xdf, 0x25, 0x97, 0xd0, 0xa2, 0xe4, 0x29, 0x4f, 0xf9, 0xd2, 0x52, 0x17, 0x69,
	0xa9, 0xed, 0x2d, 0x4c, 0xda, 0x6a, 0x68, 0xca, 0x36, 0xda, 0x49, 0xc2, 0xe1, 0x70, 0xb1, 0x9c,
	0xae, 0x47, 0xb6, 0xa2, 0xd3, 0x2d, 0x25, 0xb2, 0x15, 0x1d, 0x2f, 0x23, 0xc2, 0x12, 0xb5, 0x62,
	0x1e, 0xe5, 0xe3, 0x5b, 0x81, 0x7e, 0x01, 0x98, 0xa6, 0xcb, 0x10, 0x15, 0xa2, 0x47, 0x16, 0x3c,
	0xaf, 0x33, 0x0b, 0xb1, 0x75, 0x18, 0xe6, 0x3d, 0x8a, 0x59, 0x40, 0xf3, 0x11, 0x30, 0xbd, 0x4f,
	0x9a, 0xb3, 0xb4, 0x65, 0xba, 0x69, 0x7f, 0x03, 0xf0, 0x0c, 0xd5, 0x77, 0x43, 0x2e, 0x44, 0xcf,
	0x84, 0x0b, 0x6b, 0xeb, 0x15, 0x44, 0x98, 0xa3, 0xac, 0xb3, 0xe8, 0x66, 0x54, 0x56, 0xf4, 0x3e,
	0x09, 0xfb, 0x82, 0xfb, 0x09, 0x2a, 0xc6, 0xcc, 0x21, 0x7c, 0xdc, 0x66, 0xee, 0xf3, 0x92, 0x63,
	0xc4, 0x2a, 0x25, 0x96, 0xd1, 0x6a, 0x54, 0x62, 0xff, 0x26, 0x13, 0x4c, 0x59, 0xda, 0x6a, 0xbd,
	0xe7, 0x6c, 0xa3, 0xdf, 0x00, 0x0e, 0x06, 0x3b, 0x70, 0xf3, 0x2f, 0xc6, 0xcc, 0x8d, 0x93, 0x37,
	0x1d, 0x6e, 0x1c, 0xc2, 0x22, 0xf5, 0x26, 0x8f, 0xe6, 0xe2, 0x7a, 0x83, 0x5e, 0x27, 0x61, 0x7f,
	0xe8, 0x94, 0x41, 0x9c, 0x72, 0xfc, 0xbb, 0xbd, 0x2d, 0x73, 0xd3, 0x63, 0xf0, 0x8f, 0x28, 0xfc,
	0x32, 0x2a, 0xc6, 0x85, 0xb7, 0x43, 0xef, 0xff, 0x11, 0x80, 0x43, 0xa1, 0x82, 0xee, 0x3a, 0xe0,
	0x14, 0x5c, 0x6c, 0x33, 0x3a, 0xdd, 0x35, 0x84, 0xbb, 0xd4, 0x8c, 0x3b, 0x28, 0x17, 0xdb, 0x8c,
	0xfc, 0xd3, 0xbd, 0x83, 0x2c, 0xd8, 0x3f, 0xc8, 0x82, 0x1f, 0x07, 0x59, 0xb0, 0x7b, 0x98, 0x4d,
	0xec, 0x1f, 0x66, 0x13, 0x5f, 0x0e, 0xb3, 0x89, 0xc7, 0x05, 0x55, 0x73, 0xd6, 0xeb, 0x15, 0xb1,
	0x4a, 0x6a, 0xdd, 0xca, 0x4c, 0x35, 0xeb, 0x4c, 0xb1, 0x42, 0x2f, 0x58, 0x29, 0x67, 0xd3, 0xc4,
	0x76, 0xe5, 0x34, 0xfd, 0xf7, 0xe1, 0xfa, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x98, 0x32, 0x47,
	0xa3, 0x8b, 0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a VendorProducts by index.
	VendorProducts(ctx context.Context, in *QueryGetVendorProductsRequest, opts ...grpc.CallOption) (*QueryGetVendorProductsResponse, error)
	// Queries a list of VendorProducts items.
	VendorProductsAll(ctx context.Context, in *QueryAllVendorProductsRequest, opts ...grpc.CallOption) (*QueryAllVendorProductsResponse, error)
	// Queries a Model by index.
	Model(ctx context.Context, in *QueryGetModelRequest, opts ...grpc.CallOption) (*QueryGetModelResponse, error)
	// Queries a list of Model items.
	ModelAll(ctx context.Context, in *QueryAllModelRequest, opts ...grpc.CallOption) (*QueryAllModelResponse, error)
	// Queries a ModelVersion by index.
	ModelVersion(ctx context.Context, in *QueryGetModelVersionRequest, opts ...grpc.CallOption) (*QueryGetModelVersionResponse, error)
	// Queries a list of ModelVersion items.
	ModelVersionAll(ctx context.Context, in *QueryAllModelVersionRequest, opts ...grpc.CallOption) (*QueryAllModelVersionResponse, error)
	// Queries a ModelVersions by index.
	ModelVersions(ctx context.Context, in *QueryGetModelVersionsRequest, opts ...grpc.CallOption) (*QueryGetModelVersionsResponse, error)
	// Queries a list of ModelVersions items.
	ModelVersionsAll(ctx context.Context, in *QueryAllModelVersionsRequest, opts ...grpc.CallOption) (*QueryAllModelVersionsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) VendorProducts(ctx context.Context, in *QueryGetVendorProductsRequest, opts ...grpc.CallOption) (*QueryGetVendorProductsResponse, error) {
	out := new(QueryGetVendorProductsResponse)
	err := c.cc.Invoke(ctx, "/zigbeealliance.distributedcomplianceledger.model.Query/VendorProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VendorProductsAll(ctx context.Context, in *QueryAllVendorProductsRequest, opts ...grpc.CallOption) (*QueryAllVendorProductsResponse, error) {
	out := new(QueryAllVendorProductsResponse)
	err := c.cc.Invoke(ctx, "/zigbeealliance.distributedcomplianceledger.model.Query/VendorProductsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Model(ctx context.Context, in *QueryGetModelRequest, opts ...grpc.CallOption) (*QueryGetModelResponse, error) {
	out := new(QueryGetModelResponse)
	err := c.cc.Invoke(ctx, "/zigbeealliance.distributedcomplianceledger.model.Query/Model", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ModelAll(ctx context.Context, in *QueryAllModelRequest, opts ...grpc.CallOption) (*QueryAllModelResponse, error) {
	out := new(QueryAllModelResponse)
	err := c.cc.Invoke(ctx, "/zigbeealliance.distributedcomplianceledger.model.Query/ModelAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ModelVersion(ctx context.Context, in *QueryGetModelVersionRequest, opts ...grpc.CallOption) (*QueryGetModelVersionResponse, error) {
	out := new(QueryGetModelVersionResponse)
	err := c.cc.Invoke(ctx, "/zigbeealliance.distributedcomplianceledger.model.Query/ModelVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ModelVersionAll(ctx context.Context, in *QueryAllModelVersionRequest, opts ...grpc.CallOption) (*QueryAllModelVersionResponse, error) {
	out := new(QueryAllModelVersionResponse)
	err := c.cc.Invoke(ctx, "/zigbeealliance.distributedcomplianceledger.model.Query/ModelVersionAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ModelVersions(ctx context.Context, in *QueryGetModelVersionsRequest, opts ...grpc.CallOption) (*QueryGetModelVersionsResponse, error) {
	out := new(QueryGetModelVersionsResponse)
	err := c.cc.Invoke(ctx, "/zigbeealliance.distributedcomplianceledger.model.Query/ModelVersions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ModelVersionsAll(ctx context.Context, in *QueryAllModelVersionsRequest, opts ...grpc.CallOption) (*QueryAllModelVersionsResponse, error) {
	out := new(QueryAllModelVersionsResponse)
	err := c.cc.Invoke(ctx, "/zigbeealliance.distributedcomplianceledger.model.Query/ModelVersionsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a VendorProducts by index.
	VendorProducts(context.Context, *QueryGetVendorProductsRequest) (*QueryGetVendorProductsResponse, error)
	// Queries a list of VendorProducts items.
	VendorProductsAll(context.Context, *QueryAllVendorProductsRequest) (*QueryAllVendorProductsResponse, error)
	// Queries a Model by index.
	Model(context.Context, *QueryGetModelRequest) (*QueryGetModelResponse, error)
	// Queries a list of Model items.
	ModelAll(context.Context, *QueryAllModelRequest) (*QueryAllModelResponse, error)
	// Queries a ModelVersion by index.
	ModelVersion(context.Context, *QueryGetModelVersionRequest) (*QueryGetModelVersionResponse, error)
	// Queries a list of ModelVersion items.
	ModelVersionAll(context.Context, *QueryAllModelVersionRequest) (*QueryAllModelVersionResponse, error)
	// Queries a ModelVersions by index.
	ModelVersions(context.Context, *QueryGetModelVersionsRequest) (*QueryGetModelVersionsResponse, error)
	// Queries a list of ModelVersions items.
	ModelVersionsAll(context.Context, *QueryAllModelVersionsRequest) (*QueryAllModelVersionsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) VendorProducts(ctx context.Context, req *QueryGetVendorProductsRequest) (*QueryGetVendorProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VendorProducts not implemented")
}
func (*UnimplementedQueryServer) VendorProductsAll(ctx context.Context, req *QueryAllVendorProductsRequest) (*QueryAllVendorProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VendorProductsAll not implemented")
}
func (*UnimplementedQueryServer) Model(ctx context.Context, req *QueryGetModelRequest) (*QueryGetModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Model not implemented")
}
func (*UnimplementedQueryServer) ModelAll(ctx context.Context, req *QueryAllModelRequest) (*QueryAllModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModelAll not implemented")
}
func (*UnimplementedQueryServer) ModelVersion(ctx context.Context, req *QueryGetModelVersionRequest) (*QueryGetModelVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModelVersion not implemented")
}
func (*UnimplementedQueryServer) ModelVersionAll(ctx context.Context, req *QueryAllModelVersionRequest) (*QueryAllModelVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModelVersionAll not implemented")
}
func (*UnimplementedQueryServer) ModelVersions(ctx context.Context, req *QueryGetModelVersionsRequest) (*QueryGetModelVersionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModelVersions not implemented")
}
func (*UnimplementedQueryServer) ModelVersionsAll(ctx context.Context, req *QueryAllModelVersionsRequest) (*QueryAllModelVersionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModelVersionsAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_VendorProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetVendorProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VendorProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zigbeealliance.distributedcomplianceledger.model.Query/VendorProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VendorProducts(ctx, req.(*QueryGetVendorProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VendorProductsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllVendorProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VendorProductsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zigbeealliance.distributedcomplianceledger.model.Query/VendorProductsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VendorProductsAll(ctx, req.(*QueryAllVendorProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Model_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Model(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zigbeealliance.distributedcomplianceledger.model.Query/Model",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Model(ctx, req.(*QueryGetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ModelAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ModelAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zigbeealliance.distributedcomplianceledger.model.Query/ModelAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ModelAll(ctx, req.(*QueryAllModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ModelVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetModelVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ModelVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zigbeealliance.distributedcomplianceledger.model.Query/ModelVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ModelVersion(ctx, req.(*QueryGetModelVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ModelVersionAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllModelVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ModelVersionAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zigbeealliance.distributedcomplianceledger.model.Query/ModelVersionAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ModelVersionAll(ctx, req.(*QueryAllModelVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ModelVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetModelVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ModelVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zigbeealliance.distributedcomplianceledger.model.Query/ModelVersions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ModelVersions(ctx, req.(*QueryGetModelVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ModelVersionsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllModelVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ModelVersionsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zigbeealliance.distributedcomplianceledger.model.Query/ModelVersionsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ModelVersionsAll(ctx, req.(*QueryAllModelVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zigbeealliance.distributedcomplianceledger.model.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VendorProducts",
			Handler:    _Query_VendorProducts_Handler,
		},
		{
			MethodName: "VendorProductsAll",
			Handler:    _Query_VendorProductsAll_Handler,
		},
		{
			MethodName: "Model",
			Handler:    _Query_Model_Handler,
		},
		{
			MethodName: "ModelAll",
			Handler:    _Query_ModelAll_Handler,
		},
		{
			MethodName: "ModelVersion",
			Handler:    _Query_ModelVersion_Handler,
		},
		{
			MethodName: "ModelVersionAll",
			Handler:    _Query_ModelVersionAll_Handler,
		},
		{
			MethodName: "ModelVersions",
			Handler:    _Query_ModelVersions_Handler,
		},
		{
			MethodName: "ModelVersionsAll",
			Handler:    _Query_ModelVersionsAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model/query.proto",
}

func (m *QueryGetVendorProductsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVendorProductsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVendorProductsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Vid != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Vid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetVendorProductsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVendorProductsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVendorProductsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.VendorProducts.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllVendorProductsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllVendorProductsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllVendorProductsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllVendorProductsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllVendorProductsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllVendorProductsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.VendorProducts) > 0 {
		for iNdEx := len(m.VendorProducts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VendorProducts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetModelRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetModelRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetModelRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pid != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Pid))
		i--
		dAtA[i] = 0x10
	}
	if m.Vid != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Vid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetModelResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetModelResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetModelResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Model.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllModelRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllModelRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllModelRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllModelResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllModelResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllModelResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Model) > 0 {
		for iNdEx := len(m.Model) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Model[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetModelVersionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetModelVersionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetModelVersionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SoftwareVersion != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.SoftwareVersion))
		i--
		dAtA[i] = 0x18
	}
	if m.Pid != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Pid))
		i--
		dAtA[i] = 0x10
	}
	if m.Vid != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Vid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetModelVersionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetModelVersionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetModelVersionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ModelVersion.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllModelVersionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllModelVersionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllModelVersionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllModelVersionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllModelVersionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllModelVersionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ModelVersion) > 0 {
		for iNdEx := len(m.ModelVersion) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ModelVersion[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetModelVersionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetModelVersionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetModelVersionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pid != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Pid))
		i--
		dAtA[i] = 0x10
	}
	if m.Vid != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Vid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetModelVersionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetModelVersionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetModelVersionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ModelVersions.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllModelVersionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllModelVersionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllModelVersionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllModelVersionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllModelVersionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllModelVersionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ModelVersions) > 0 {
		for iNdEx := len(m.ModelVersions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ModelVersions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetVendorProductsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Vid != 0 {
		n += 1 + sovQuery(uint64(m.Vid))
	}
	return n
}

func (m *QueryGetVendorProductsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.VendorProducts.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllVendorProductsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllVendorProductsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.VendorProducts) > 0 {
		for _, e := range m.VendorProducts {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetModelRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Vid != 0 {
		n += 1 + sovQuery(uint64(m.Vid))
	}
	if m.Pid != 0 {
		n += 1 + sovQuery(uint64(m.Pid))
	}
	return n
}

func (m *QueryGetModelResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Model.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllModelRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllModelResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Model) > 0 {
		for _, e := range m.Model {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetModelVersionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Vid != 0 {
		n += 1 + sovQuery(uint64(m.Vid))
	}
	if m.Pid != 0 {
		n += 1 + sovQuery(uint64(m.Pid))
	}
	if m.SoftwareVersion != 0 {
		n += 1 + sovQuery(uint64(m.SoftwareVersion))
	}
	return n
}

func (m *QueryGetModelVersionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ModelVersion.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllModelVersionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllModelVersionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ModelVersion) > 0 {
		for _, e := range m.ModelVersion {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetModelVersionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Vid != 0 {
		n += 1 + sovQuery(uint64(m.Vid))
	}
	if m.Pid != 0 {
		n += 1 + sovQuery(uint64(m.Pid))
	}
	return n
}

func (m *QueryGetModelVersionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ModelVersions.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllModelVersionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllModelVersionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ModelVersions) > 0 {
		for _, e := range m.ModelVersions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetVendorProductsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVendorProductsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVendorProductsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vid", wireType)
			}
			m.Vid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Vid |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVendorProductsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVendorProductsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVendorProductsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorProducts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VendorProducts.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllVendorProductsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllVendorProductsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllVendorProductsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllVendorProductsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllVendorProductsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllVendorProductsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorProducts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VendorProducts = append(m.VendorProducts, VendorProducts{})
			if err := m.VendorProducts[len(m.VendorProducts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetModelRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetModelRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetModelRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vid", wireType)
			}
			m.Vid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Vid |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pid", wireType)
			}
			m.Pid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Pid |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetModelResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetModelResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetModelResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Model", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Model.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllModelRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllModelRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllModelRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllModelResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllModelResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllModelResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Model", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Model = append(m.Model, Model{})
			if err := m.Model[len(m.Model)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetModelVersionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetModelVersionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetModelVersionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vid", wireType)
			}
			m.Vid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Vid |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pid", wireType)
			}
			m.Pid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Pid |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SoftwareVersion", wireType)
			}
			m.SoftwareVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SoftwareVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetModelVersionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetModelVersionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetModelVersionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelVersion", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ModelVersion.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllModelVersionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllModelVersionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllModelVersionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllModelVersionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllModelVersionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllModelVersionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelVersion", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelVersion = append(m.ModelVersion, ModelVersion{})
			if err := m.ModelVersion[len(m.ModelVersion)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetModelVersionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetModelVersionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetModelVersionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vid", wireType)
			}
			m.Vid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Vid |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pid", wireType)
			}
			m.Pid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Pid |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetModelVersionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetModelVersionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetModelVersionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelVersions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ModelVersions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllModelVersionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllModelVersionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllModelVersionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllModelVersionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllModelVersionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllModelVersionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelVersions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelVersions = append(m.ModelVersions, ModelVersions{})
			if err := m.ModelVersions[len(m.ModelVersions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
