---
# Copyright 2022 DSR Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

dependency:
  name: galaxy
  options:
    role-file: ../../../galaxy-requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint -c ../../../../.yaml-lint.yml .
platforms:
  - name: node0
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - genesis
  - name: node1
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - genesis
  - name: node2
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - genesis
  - name: node3
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - genesis
provisioner:
  name: ansible
  inventory:
    host_vars:
      node0:
        accounts:
          - name: jack
            passphrase: test1234
            roles:
              - NodeAdmin
              - Trustee
      node1:
        accounts:
          - name: alice
            passphrase: test1234
            roles:
              - NodeAdmin
              - Trustee
      node2:
        accounts:
          - name: bob
            passphrase: test1234
            roles:
              - NodeAdmin
              - Trustee
      node3:
        accounts:
          - name: anna
            passphrase: test1234
            roles:
              - NodeAdmin
verifier:
  name: testinfra
  lint:
    name: flake8
