// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dclupgrade/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/x/upgrade/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgProposeUpgrade struct {
	Creator string     `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty" validate:"required"`
	Plan    types.Plan `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan"`
	Info    string     `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty" validate:"max=4096"`
	Time    int64      `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (m *MsgProposeUpgrade) Reset()         { *m = MsgProposeUpgrade{} }
func (m *MsgProposeUpgrade) String() string { return proto.CompactTextString(m) }
func (*MsgProposeUpgrade) ProtoMessage()    {}
func (*MsgProposeUpgrade) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6618e43a1731fe5, []int{0}
}
func (m *MsgProposeUpgrade) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgProposeUpgrade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgProposeUpgrade.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgProposeUpgrade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgProposeUpgrade.Merge(m, src)
}
func (m *MsgProposeUpgrade) XXX_Size() int {
	return m.Size()
}
func (m *MsgProposeUpgrade) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgProposeUpgrade.DiscardUnknown(m)
}

var xxx_messageInfo_MsgProposeUpgrade proto.InternalMessageInfo

func (m *MsgProposeUpgrade) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgProposeUpgrade) GetPlan() types.Plan {
	if m != nil {
		return m.Plan
	}
	return types.Plan{}
}

func (m *MsgProposeUpgrade) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *MsgProposeUpgrade) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type MsgProposeUpgradeResponse struct {
}

func (m *MsgProposeUpgradeResponse) Reset()         { *m = MsgProposeUpgradeResponse{} }
func (m *MsgProposeUpgradeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgProposeUpgradeResponse) ProtoMessage()    {}
func (*MsgProposeUpgradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6618e43a1731fe5, []int{1}
}
func (m *MsgProposeUpgradeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgProposeUpgradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgProposeUpgradeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgProposeUpgradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgProposeUpgradeResponse.Merge(m, src)
}
func (m *MsgProposeUpgradeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgProposeUpgradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgProposeUpgradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgProposeUpgradeResponse proto.InternalMessageInfo

type MsgApproveUpgrade struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty" validate:"required"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" validate:"required"`
	Info    string `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty" validate:"max=4096"`
	Time    int64  `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (m *MsgApproveUpgrade) Reset()         { *m = MsgApproveUpgrade{} }
func (m *MsgApproveUpgrade) String() string { return proto.CompactTextString(m) }
func (*MsgApproveUpgrade) ProtoMessage()    {}
func (*MsgApproveUpgrade) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6618e43a1731fe5, []int{2}
}
func (m *MsgApproveUpgrade) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgApproveUpgrade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgApproveUpgrade.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgApproveUpgrade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgApproveUpgrade.Merge(m, src)
}
func (m *MsgApproveUpgrade) XXX_Size() int {
	return m.Size()
}
func (m *MsgApproveUpgrade) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgApproveUpgrade.DiscardUnknown(m)
}

var xxx_messageInfo_MsgApproveUpgrade proto.InternalMessageInfo

func (m *MsgApproveUpgrade) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgApproveUpgrade) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgApproveUpgrade) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *MsgApproveUpgrade) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type MsgApproveUpgradeResponse struct {
}

func (m *MsgApproveUpgradeResponse) Reset()         { *m = MsgApproveUpgradeResponse{} }
func (m *MsgApproveUpgradeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgApproveUpgradeResponse) ProtoMessage()    {}
func (*MsgApproveUpgradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6618e43a1731fe5, []int{3}
}
func (m *MsgApproveUpgradeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgApproveUpgradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgApproveUpgradeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgApproveUpgradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgApproveUpgradeResponse.Merge(m, src)
}
func (m *MsgApproveUpgradeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgApproveUpgradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgApproveUpgradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgApproveUpgradeResponse proto.InternalMessageInfo

type MsgRejectUpgrade struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Info    string `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty" validate:"max=4096"`
	Time    int64  `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (m *MsgRejectUpgrade) Reset()         { *m = MsgRejectUpgrade{} }
func (m *MsgRejectUpgrade) String() string { return proto.CompactTextString(m) }
func (*MsgRejectUpgrade) ProtoMessage()    {}
func (*MsgRejectUpgrade) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6618e43a1731fe5, []int{4}
}
func (m *MsgRejectUpgrade) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRejectUpgrade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRejectUpgrade.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRejectUpgrade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRejectUpgrade.Merge(m, src)
}
func (m *MsgRejectUpgrade) XXX_Size() int {
	return m.Size()
}
func (m *MsgRejectUpgrade) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRejectUpgrade.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRejectUpgrade proto.InternalMessageInfo

func (m *MsgRejectUpgrade) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRejectUpgrade) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgRejectUpgrade) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *MsgRejectUpgrade) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type MsgRejectUpgradeResponse struct {
}

func (m *MsgRejectUpgradeResponse) Reset()         { *m = MsgRejectUpgradeResponse{} }
func (m *MsgRejectUpgradeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRejectUpgradeResponse) ProtoMessage()    {}
func (*MsgRejectUpgradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6618e43a1731fe5, []int{5}
}
func (m *MsgRejectUpgradeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRejectUpgradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRejectUpgradeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRejectUpgradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRejectUpgradeResponse.Merge(m, src)
}
func (m *MsgRejectUpgradeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRejectUpgradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRejectUpgradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRejectUpgradeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgProposeUpgrade)(nil), "zigbeealliance.distributedcomplianceledger.dclupgrade.MsgProposeUpgrade")
	proto.RegisterType((*MsgProposeUpgradeResponse)(nil), "zigbeealliance.distributedcomplianceledger.dclupgrade.MsgProposeUpgradeResponse")
	proto.RegisterType((*MsgApproveUpgrade)(nil), "zigbeealliance.distributedcomplianceledger.dclupgrade.MsgApproveUpgrade")
	proto.RegisterType((*MsgApproveUpgradeResponse)(nil), "zigbeealliance.distributedcomplianceledger.dclupgrade.MsgApproveUpgradeResponse")
	proto.RegisterType((*MsgRejectUpgrade)(nil), "zigbeealliance.distributedcomplianceledger.dclupgrade.MsgRejectUpgrade")
	proto.RegisterType((*MsgRejectUpgradeResponse)(nil), "zigbeealliance.distributedcomplianceledger.dclupgrade.MsgRejectUpgradeResponse")
}

func init() { proto.RegisterFile("dclupgrade/tx.proto", fileDescriptor_c6618e43a1731fe5) }

var fileDescriptor_c6618e43a1731fe5 = []byte{
	// 506 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xc1, 0x8a, 0xd3, 0x40,
	0x18, 0xc7, 0x3b, 0x36, 0x28, 0x8e, 0x28, 0x9a, 0x5d, 0x30, 0x1b, 0x25, 0x5b, 0x82, 0x87, 0xc2,
	0xd2, 0xc4, 0x5d, 0x75, 0x41, 0xc1, 0xc3, 0xf6, 0xa2, 0x22, 0xc5, 0x12, 0xf1, 0xe2, 0x45, 0x26,
	0xc9, 0xe7, 0x38, 0x92, 0x64, 0xe2, 0xcc, 0xb4, 0x54, 0x6f, 0x3e, 0x81, 0xbe, 0x86, 0xe0, 0xd1,
	0x87, 0xd8, 0x83, 0x87, 0xc5, 0x8b, 0x9e, 0x16, 0x69, 0xdf, 0xc0, 0x27, 0x10, 0x33, 0x9d, 0x6d,
	0xd3, 0x7a, 0xda, 0x76, 0x6f, 0xf3, 0xf5, 0xfb, 0xe6, 0xff, 0xff, 0xfd, 0xe9, 0x97, 0xc1, 0x1b,
	0x69, 0x92, 0x0d, 0x4a, 0x2a, 0x48, 0x0a, 0xa1, 0x1a, 0x05, 0xa5, 0xe0, 0x8a, 0xdb, 0xf7, 0x3e,
	0x30, 0x1a, 0x03, 0x90, 0x2c, 0x63, 0xa4, 0x48, 0x20, 0x48, 0x99, 0x54, 0x82, 0xc5, 0x03, 0x05,
	0x69, 0xc2, 0xf3, 0x52, 0xff, 0x9a, 0x41, 0x4a, 0x41, 0x04, 0xb3, 0xfb, 0xee, 0x26, 0xe5, 0x94,
	0x57, 0x0a, 0xe1, 0xbf, 0x93, 0x16, 0x73, 0xb7, 0x12, 0x2e, 0x73, 0x2e, 0x5f, 0xe9, 0x86, 0x2e,
	0xa6, 0xad, 0x5b, 0xba, 0x0a, 0x0d, 0xc0, 0x70, 0x37, 0x06, 0x45, 0x76, 0x4d, 0xad, 0xa7, 0xfc,
	0x9f, 0x08, 0x5f, 0xeb, 0x49, 0xda, 0x17, 0xbc, 0xe4, 0x12, 0x5e, 0xe8, 0x9e, 0xfd, 0x04, 0x5f,
	0x48, 0x04, 0x10, 0xc5, 0x85, 0x83, 0x5a, 0xa8, 0x7d, 0xb1, 0x1b, 0xfe, 0x39, 0xde, 0xde, 0x18,
	0x92, 0x8c, 0xa5, 0x44, 0xc1, 0x03, 0x5f, 0xc0, 0xbb, 0x01, 0x13, 0x90, 0xfa, 0x3f, 0xbe, 0x75,
	0x36, 0xa7, 0xae, 0x07, 0x69, 0x2a, 0x40, 0xca, 0xe7, 0x4a, 0xb0, 0x82, 0x46, 0xe6, 0xbe, 0xbd,
	0x8f, 0xad, 0x32, 0x23, 0x85, 0x73, 0xae, 0x85, 0xda, 0x97, 0xf6, 0x6e, 0x06, 0xd3, 0x69, 0x43,
	0x31, 0xa5, 0x0a, 0xfa, 0x19, 0x29, 0xba, 0xd6, 0xe1, 0xf1, 0x76, 0x23, 0xaa, 0xe6, 0xed, 0x1d,
	0x6c, 0xb1, 0xe2, 0x35, 0x77, 0x9a, 0x95, 0xff, 0xf5, 0xba, 0x7f, 0x4e, 0x46, 0x0f, 0xef, 0xde,
	0xbe, 0xbf, 0xef, 0x47, 0xd5, 0x90, 0x6d, 0x63, 0x4b, 0xb1, 0x1c, 0x1c, 0xab, 0x85, 0xda, 0xcd,
	0xa8, 0x3a, 0xfb, 0x37, 0xf0, 0xd6, 0x52, 0xb0, 0x08, 0x64, 0xc9, 0x0b, 0x09, 0xfe, 0x77, 0x1d,
	0xfb, 0xa0, 0x2c, 0x05, 0x1f, 0x9e, 0x45, 0xec, 0x1d, 0x6c, 0x15, 0x24, 0x87, 0x2a, 0xf6, 0x12,
	0xfe, 0x89, 0x4e, 0x54, 0x0d, 0xad, 0x2b, 0x6b, 0x3d, 0xcd, 0x49, 0xd6, 0x8f, 0x08, 0x5f, 0xed,
	0x49, 0x1a, 0xc1, 0x5b, 0x48, 0x94, 0x89, 0xea, 0x2c, 0x44, 0x9d, 0x91, 0xdb, 0xf3, 0xe4, 0xeb,
	0x02, 0x74, 0xb1, 0xb3, 0x88, 0x60, 0xf8, 0xf6, 0x3e, 0x59, 0xb8, 0xd9, 0x93, 0xd4, 0xfe, 0x8a,
	0xf0, 0x95, 0x85, 0x3d, 0x7c, 0x1c, 0x9c, 0xea, 0x63, 0x09, 0x96, 0xfe, 0x78, 0xb7, 0xbf, 0x2e,
	0x25, 0x83, 0x5d, 0xe1, 0x2e, 0xec, 0xcf, 0x0a, 0xb8, 0x75, 0xa5, 0x55, 0x70, 0xff, 0xbf, 0x05,
	0xf6, 0x17, 0x84, 0x2f, 0xd7, 0x57, 0xe0, 0xd1, 0xe9, 0x3d, 0x6a, 0x42, 0xee, 0xb3, 0x35, 0x09,
	0x19, 0xd6, 0x2e, 0x1c, 0x8e, 0x3d, 0x74, 0x34, 0xf6, 0xd0, 0xef, 0xb1, 0x87, 0x3e, 0x4f, 0xbc,
	0xc6, 0xd1, 0xc4, 0x6b, 0xfc, 0x9a, 0x78, 0x8d, 0x97, 0x4f, 0x29, 0x53, 0x6f, 0x06, 0x71, 0x90,
	0xf0, 0x3c, 0xd4, 0xa6, 0x1d, 0xe3, 0x1a, 0xce, 0xb9, 0x76, 0x66, 0xb6, 0x1d, 0xed, 0x1b, 0x8e,
	0xc2, 0xf9, 0xc7, 0xf8, 0x7d, 0x09, 0x32, 0x3e, 0x5f, 0x3d, 0x81, 0x77, 0xfe, 0x06, 0x00, 0x00,
	0xff, 0xff, 0x59, 0x25, 0x85, 0x35, 0xa7, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	ProposeUpgrade(ctx context.Context, in *MsgProposeUpgrade, opts ...grpc.CallOption) (*MsgProposeUpgradeResponse, error)
	ApproveUpgrade(ctx context.Context, in *MsgApproveUpgrade, opts ...grpc.CallOption) (*MsgApproveUpgradeResponse, error)
	RejectUpgrade(ctx context.Context, in *MsgRejectUpgrade, opts ...grpc.CallOption) (*MsgRejectUpgradeResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ProposeUpgrade(ctx context.Context, in *MsgProposeUpgrade, opts ...grpc.CallOption) (*MsgProposeUpgradeResponse, error) {
	out := new(MsgProposeUpgradeResponse)
	err := c.cc.Invoke(ctx, "/zigbeealliance.distributedcomplianceledger.dclupgrade.Msg/ProposeUpgrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ApproveUpgrade(ctx context.Context, in *MsgApproveUpgrade, opts ...grpc.CallOption) (*MsgApproveUpgradeResponse, error) {
	out := new(MsgApproveUpgradeResponse)
	err := c.cc.Invoke(ctx, "/zigbeealliance.distributedcomplianceledger.dclupgrade.Msg/ApproveUpgrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RejectUpgrade(ctx context.Context, in *MsgRejectUpgrade, opts ...grpc.CallOption) (*MsgRejectUpgradeResponse, error) {
	out := new(MsgRejectUpgradeResponse)
	err := c.cc.Invoke(ctx, "/zigbeealliance.distributedcomplianceledger.dclupgrade.Msg/RejectUpgrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	ProposeUpgrade(context.Context, *MsgProposeUpgrade) (*MsgProposeUpgradeResponse, error)
	ApproveUpgrade(context.Context, *MsgApproveUpgrade) (*MsgApproveUpgradeResponse, error)
	RejectUpgrade(context.Context, *MsgRejectUpgrade) (*MsgRejectUpgradeResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ProposeUpgrade(ctx context.Context, req *MsgProposeUpgrade) (*MsgProposeUpgradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposeUpgrade not implemented")
}
func (*UnimplementedMsgServer) ApproveUpgrade(ctx context.Context, req *MsgApproveUpgrade) (*MsgApproveUpgradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveUpgrade not implemented")
}
func (*UnimplementedMsgServer) RejectUpgrade(ctx context.Context, req *MsgRejectUpgrade) (*MsgRejectUpgradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectUpgrade not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ProposeUpgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgProposeUpgrade)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ProposeUpgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zigbeealliance.distributedcomplianceledger.dclupgrade.Msg/ProposeUpgrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ProposeUpgrade(ctx, req.(*MsgProposeUpgrade))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ApproveUpgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgApproveUpgrade)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ApproveUpgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zigbeealliance.distributedcomplianceledger.dclupgrade.Msg/ApproveUpgrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ApproveUpgrade(ctx, req.(*MsgApproveUpgrade))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RejectUpgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRejectUpgrade)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RejectUpgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zigbeealliance.distributedcomplianceledger.dclupgrade.Msg/RejectUpgrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RejectUpgrade(ctx, req.(*MsgRejectUpgrade))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zigbeealliance.distributedcomplianceledger.dclupgrade.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProposeUpgrade",
			Handler:    _Msg_ProposeUpgrade_Handler,
		},
		{
			MethodName: "ApproveUpgrade",
			Handler:    _Msg_ApproveUpgrade_Handler,
		},
		{
			MethodName: "RejectUpgrade",
			Handler:    _Msg_RejectUpgrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dclupgrade/tx.proto",
}

func (m *MsgProposeUpgrade) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgProposeUpgrade) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgProposeUpgrade) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Time != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Time))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Info) > 0 {
		i -= len(m.Info)
		copy(dAtA[i:], m.Info)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Info)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.Plan.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgProposeUpgradeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgProposeUpgradeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgProposeUpgradeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgApproveUpgrade) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgApproveUpgrade) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgApproveUpgrade) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Time != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Time))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Info) > 0 {
		i -= len(m.Info)
		copy(dAtA[i:], m.Info)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Info)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgApproveUpgradeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgApproveUpgradeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgApproveUpgradeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRejectUpgrade) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRejectUpgrade) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRejectUpgrade) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Time != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Time))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Info) > 0 {
		i -= len(m.Info)
		copy(dAtA[i:], m.Info)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Info)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRejectUpgradeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRejectUpgradeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRejectUpgradeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgProposeUpgrade) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Plan.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.Info)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Time != 0 {
		n += 1 + sovTx(uint64(m.Time))
	}
	return n
}

func (m *MsgProposeUpgradeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgApproveUpgrade) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Info)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Time != 0 {
		n += 1 + sovTx(uint64(m.Time))
	}
	return n
}

func (m *MsgApproveUpgradeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRejectUpgrade) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Info)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Time != 0 {
		n += 1 + sovTx(uint64(m.Time))
	}
	return n
}

func (m *MsgRejectUpgradeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgProposeUpgrade) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgProposeUpgrade: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgProposeUpgrade: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Plan", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Plan.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Info = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			m.Time = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Time |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgProposeUpgradeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgProposeUpgradeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgProposeUpgradeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgApproveUpgrade) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgApproveUpgrade: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgApproveUpgrade: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Info = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			m.Time = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Time |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgApproveUpgradeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgApproveUpgradeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgApproveUpgradeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRejectUpgrade) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRejectUpgrade: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRejectUpgrade: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Info = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			m.Time = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Time |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRejectUpgradeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRejectUpgradeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRejectUpgradeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
