# Copyright 2020 DSR Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# Builds dcld and cosmovisor applications for further use on the machine
# where the new node will be deployed.
# The resulting image is used only for getting the build artifacts from
# a container based on it. Containers based on this image are never run.
################################################################################
FROM golang:bullseye

WORKDIR /go/src/dc-ledger
COPY app ./app/
COPY cmd ./cmd/
COPY testutil ./testutil/
COPY utils ./utils/
COPY x ./x/
COPY go.mod go.sum Makefile ./
COPY docs/docs.go ./docs/
COPY docs/static ./docs/static/

ARG DCL_VERSION
ARG DCL_COMMIT
RUN LEDGER_ENABLED=false make

RUN go install github.com/cosmos/cosmos-sdk/cosmovisor/cmd/cosmovisor@v1.0.0
