package cli

const (
	FlagCertificate              = "certificate"
	FlagCertificateShortcut      = "c"
	FlagSubject                  = "subject"
	FlagSubjectShortcut          = "u"
	FlagSubjectKeyID             = "subject-key-id"
	FlagSubjectKeyIDShortcut     = "k"
	FlagSerialNumber             = "serial-number"
	FlagSerialNumberShortcut     = "n"
	FlagRootSubject              = "root-subject"
	FlagRootSubjectShortcut      = "s"
	FlagRootSubjectKeyID         = "root-subject-key-id"
	FlagRootSubjectKeyIDShortcut = "i"
	FlagInfo                     = "info"
	FlagInfoUsage                = "Optional information/notes for approval, proposal or revocation"
	FlagVid                      = "vid"
	FlagPid                      = "pid"
	FlagIsPAA                    = "is-paa"
	FlagDataURL                  = "data-url"
	FlagDataFileSize             = "data-file-size"
	FlagDataDigest               = "data-digest"
	FlagDataDigestType           = "data-digest-type"
	FlagRevocationType           = "revocation-type"
	FlagLabel                    = "label"
	FlagLabelShortcut            = "l"
	FlagIssuerSubjectKeyID       = "issuer-subject-key-id"
	FlagRevokeChild              = "revoke-child"
	FlagRevokeChildShortcut      = "r"
	FlagCertificateSchemaVersion = "certificate-schema-version"
	FlagCertificateDelegator     = "certificate-delegator"
	FlagIsVVSC                   = "is-vvsc"
)
