// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pki/types/approved_certificates_by_subject_key_id.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ApprovedCertificatesBySubjectKeyId struct {
	SubjectKeyId string         `protobuf:"bytes,1,opt,name=subjectKeyId,proto3" json:"subjectKeyId,omitempty"`
	Certs        []*Certificate `protobuf:"bytes,2,rep,name=certs,proto3" json:"certs,omitempty"`
}

func (m *ApprovedCertificatesBySubjectKeyId) Reset()         { *m = ApprovedCertificatesBySubjectKeyId{} }
func (m *ApprovedCertificatesBySubjectKeyId) String() string { return proto.CompactTextString(m) }
func (*ApprovedCertificatesBySubjectKeyId) ProtoMessage()    {}
func (*ApprovedCertificatesBySubjectKeyId) Descriptor() ([]byte, []int) {
	return fileDescriptor_58fc71280f93a310, []int{0}
}
func (m *ApprovedCertificatesBySubjectKeyId) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ApprovedCertificatesBySubjectKeyId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ApprovedCertificatesBySubjectKeyId.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ApprovedCertificatesBySubjectKeyId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApprovedCertificatesBySubjectKeyId.Merge(m, src)
}
func (m *ApprovedCertificatesBySubjectKeyId) XXX_Size() int {
	return m.Size()
}
func (m *ApprovedCertificatesBySubjectKeyId) XXX_DiscardUnknown() {
	xxx_messageInfo_ApprovedCertificatesBySubjectKeyId.DiscardUnknown(m)
}

var xxx_messageInfo_ApprovedCertificatesBySubjectKeyId proto.InternalMessageInfo

func (m *ApprovedCertificatesBySubjectKeyId) GetSubjectKeyId() string {
	if m != nil {
		return m.SubjectKeyId
	}
	return ""
}

func (m *ApprovedCertificatesBySubjectKeyId) GetCerts() []*Certificate {
	if m != nil {
		return m.Certs
	}
	return nil
}

func init() {
	proto.RegisterType((*ApprovedCertificatesBySubjectKeyId)(nil), "pki.types.ApprovedCertificatesBySubjectKeyId")
}

func init() {
	proto.RegisterFile("pki/types/approved_certificates_by_subject_key_id.proto", fileDescriptor_58fc71280f93a310)
}

var fileDescriptor_58fc71280f93a310 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xcf, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0x05, 0xd0, 0x1a, 0x04, 0x52, 0x03, 0x53, 0x06, 0x54, 0x81, 0x64, 0x55, 0x99, 0x3a, 0x10,
	0x5b, 0x82, 0x81, 0x99, 0xc2, 0x82, 0xd8, 0xca, 0xc6, 0x80, 0x15, 0xdb, 0x8f, 0xf0, 0x48, 0x8a,
	0x2d, 0xdb, 0xa9, 0x30, 0x5f, 0xc1, 0x67, 0x31, 0x76, 0x64, 0x44, 0xc9, 0x8f, 0x20, 0x1a, 0x54,
	0xc2, 0xe8, 0xa7, 0x7b, 0x8f, 0x7c, 0x93, 0x0b, 0x5b, 0x21, 0x0f, 0xd1, 0x82, 0xe7, 0x85, 0xb5,
	0xce, 0xac, 0x40, 0x0b, 0x05, 0x2e, 0xe0, 0x23, 0xaa, 0x22, 0x80, 0x17, 0x32, 0x0a, 0xdf, 0xc8,
	0x67, 0x50, 0x41, 0x54, 0x10, 0x05, 0x6a, 0x66, 0x9d, 0x09, 0x26, 0x1d, 0xdb, 0x0a, 0xd9, 0xa6,
	0x78, 0x7c, 0xf2, 0x67, 0x0c, 0xaa, 0x7d, 0x2e, 0x5b, 0x25, 0xd9, 0xe5, 0x2f, 0x7c, 0x35, 0x70,
	0xe7, 0xf1, 0xae, 0x57, 0x6f, 0x21, 0xde, 0xe8, 0x34, 0x4b, 0x0e, 0xfd, 0xe0, 0x3d, 0x21, 0x53,
	0x32, 0x1b, 0x2f, 0xfe, 0xdd, 0xd2, 0xd3, 0x64, 0xef, 0x87, 0xf7, 0x93, 0x9d, 0xe9, 0xee, 0xec,
	0xe0, 0xec, 0x88, 0x6d, 0x7f, 0xc0, 0x06, 0xf2, 0xa2, 0x0f, 0xcd, 0x1f, 0x3e, 0x5a, 0x4a, 0xd6,
	0x2d, 0x25, 0x5f, 0x2d, 0x25, 0xef, 0x1d, 0x1d, 0xad, 0x3b, 0x3a, 0xfa, 0xec, 0xe8, 0xe8, 0xfe,
	0xba, 0xc4, 0xf0, 0xd4, 0x48, 0xa6, 0xcc, 0x92, 0xbf, 0x61, 0x29, 0x01, 0xf2, 0xa2, 0xae, 0xb1,
	0x78, 0x51, 0xc0, 0x35, 0xfa, 0xe0, 0x50, 0x36, 0x01, 0x74, 0xae, 0xcc, 0xd2, 0xf6, 0xe7, 0xbc,
	0x06, 0x5d, 0x82, 0xe3, 0xaf, 0x7c, 0xbb, 0x54, 0xee, 0x6f, 0xe6, 0x9d, 0x7f, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x19, 0xf3, 0x0b, 0x17, 0x41, 0x01, 0x00, 0x00,
}

func (m *ApprovedCertificatesBySubjectKeyId) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ApprovedCertificatesBySubjectKeyId) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ApprovedCertificatesBySubjectKeyId) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Certs) > 0 {
		for iNdEx := len(m.Certs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Certs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintApprovedCertificatesBySubjectKeyId(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.SubjectKeyId) > 0 {
		i -= len(m.SubjectKeyId)
		copy(dAtA[i:], m.SubjectKeyId)
		i = encodeVarintApprovedCertificatesBySubjectKeyId(dAtA, i, uint64(len(m.SubjectKeyId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintApprovedCertificatesBySubjectKeyId(dAtA []byte, offset int, v uint64) int {
	offset -= sovApprovedCertificatesBySubjectKeyId(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ApprovedCertificatesBySubjectKeyId) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SubjectKeyId)
	if l > 0 {
		n += 1 + l + sovApprovedCertificatesBySubjectKeyId(uint64(l))
	}
	if len(m.Certs) > 0 {
		for _, e := range m.Certs {
			l = e.Size()
			n += 1 + l + sovApprovedCertificatesBySubjectKeyId(uint64(l))
		}
	}
	return n
}

func sovApprovedCertificatesBySubjectKeyId(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApprovedCertificatesBySubjectKeyId(x uint64) (n int) {
	return sovApprovedCertificatesBySubjectKeyId(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ApprovedCertificatesBySubjectKeyId) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApprovedCertificatesBySubjectKeyId
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ApprovedCertificatesBySubjectKeyId: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ApprovedCertificatesBySubjectKeyId: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubjectKeyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovedCertificatesBySubjectKeyId
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovedCertificatesBySubjectKeyId
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovedCertificatesBySubjectKeyId
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubjectKeyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Certs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovedCertificatesBySubjectKeyId
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApprovedCertificatesBySubjectKeyId
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApprovedCertificatesBySubjectKeyId
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Certs = append(m.Certs, &Certificate{})
			if err := m.Certs[len(m.Certs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApprovedCertificatesBySubjectKeyId(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApprovedCertificatesBySubjectKeyId
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApprovedCertificatesBySubjectKeyId(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApprovedCertificatesBySubjectKeyId
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApprovedCertificatesBySubjectKeyId
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApprovedCertificatesBySubjectKeyId
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApprovedCertificatesBySubjectKeyId
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApprovedCertificatesBySubjectKeyId
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApprovedCertificatesBySubjectKeyId
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApprovedCertificatesBySubjectKeyId        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApprovedCertificatesBySubjectKeyId          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApprovedCertificatesBySubjectKeyId = fmt.Errorf("proto: unexpected end of group")
)
