// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zigbeealliance/distributedcomplianceledger/validator/validator.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Validator struct {
	// the account address of validator owner
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// description of the validator
	Description *Description `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// the consensus public key of the tendermint validator
	PubKey *types.Any `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	// validator consensus power
	Power int32 `protobuf:"varint,4,opt,name=power,proto3" json:"power,omitempty"`
	// has the validator been removed from validator set
	Jailed bool `protobuf:"varint,5,opt,name=jailed,proto3" json:"jailed,omitempty"`
	// the reason of validator jailing
	JailedReason  string `protobuf:"bytes,6,opt,name=jailedReason,proto3" json:"jailedReason,omitempty"`
	SchemaVersion uint32 `protobuf:"varint,7,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
}

func (m *Validator) Reset()      { *m = Validator{} }
func (*Validator) ProtoMessage() {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_dac29b5a8b0a342e, []int{0}
}
func (m *Validator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return m.Size()
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Validator)(nil), "zigbeealliance.distributedcomplianceledger.validator.Validator")
}

func init() {
	proto.RegisterFile("zigbeealliance/distributedcomplianceledger/validator/validator.proto", fileDescriptor_dac29b5a8b0a342e)
}

var fileDescriptor_dac29b5a8b0a342e = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x7d, 0x85, 0x04, 0x7a, 0x6d, 0x17, 0x2b, 0x42, 0x6e, 0x07, 0xc7, 0xaa, 0x18, 0xbc,
	0xe4, 0x2c, 0x01, 0x13, 0x5b, 0xa2, 0xaa, 0x03, 0x2c, 0xc8, 0x48, 0x1d, 0x58, 0xd0, 0xf9, 0xee,
	0x71, 0x3d, 0xe4, 0xf8, 0x59, 0x77, 0x17, 0x8a, 0xf9, 0x04, 0x8c, 0x8c, 0x8c, 0xf9, 0x10, 0x7c,
	0x08, 0xc4, 0x54, 0x31, 0x31, 0xa2, 0x64, 0x61, 0xe2, 0x33, 0xa0, 0xf8, 0x5c, 0xe2, 0x48, 0x88,
	0xa1, 0xdb, 0x7b, 0xff, 0xe7, 0xf7, 0xb3, 0xfd, 0x7b, 0xf4, 0xec, 0x83, 0x56, 0x05, 0x00, 0x2f,
	0x4b, 0xcd, 0x2b, 0x01, 0x99, 0xd4, 0xd6, 0x19, 0x5d, 0x2c, 0x1c, 0x48, 0x81, 0xf3, 0xda, 0xa7,
	0x25, 0x48, 0x05, 0x26, 0x7b, 0xc7, 0x4b, 0x2d, 0xb9, 0xc3, 0x5e, 0xc5, 0x6a, 0x83, 0x0e, 0xc3,
	0x27, 0xbb, 0x14, 0xf6, 0x1f, 0x0a, 0xfb, 0xbb, 0x7b, 0x72, 0xac, 0x10, 0x55, 0x09, 0x59, 0xcb,
	0x28, 0x16, 0x6f, 0x32, 0x5e, 0x35, 0x1e, 0x78, 0x32, 0x52, 0xa8, 0xb0, 0x2d, 0xb3, 0x4d, 0xd5,
	0xa5, 0xc7, 0x02, 0xed, 0x1c, 0xed, 0x6b, 0x3f, 0xf0, 0x4d, 0x37, 0x3a, 0xbf, 0xd5, 0x7f, 0x48,
	0xb0, 0xc2, 0xe8, 0xda, 0x69, 0xac, 0x3c, 0xe7, 0xf4, 0xf7, 0x1e, 0xdd, 0xbf, 0xb8, 0x99, 0x87,
	0x8c, 0x0e, 0xf0, 0xaa, 0x02, 0x13, 0x91, 0x84, 0xa4, 0xfb, 0xb3, 0xe8, 0xfb, 0x97, 0xc9, 0xa8,
	0x7b, 0xed, 0x54, 0x4a, 0x03, 0xd6, 0xbe, 0x74, 0x46, 0x57, 0x2a, 0xf7, 0x8f, 0x85, 0x82, 0x1e,
	0xf4, 0x90, 0xd1, 0x5e, 0x42, 0xd2, 0x83, 0x47, 0x53, 0x76, 0x1b, 0x3b, 0xec, 0x6c, 0x0b, 0xca,
	0xfb, 0xd4, 0xf0, 0x9c, 0x0e, 0xeb, 0x45, 0xf1, 0x1c, 0x9a, 0xe8, 0x4e, 0xcb, 0x1f, 0x31, 0xef,
	0x91, 0xdd, 0x78, 0x64, 0xd3, 0xaa, 0x99, 0x45, 0xdf, 0xb6, 0xdf, 0x2a, 0x4c, 0x53, 0x3b, 0x64,
	0x2f, 0xda, 0xad, 0xbc, 0xdb, 0x0e, 0x47, 0x74, 0x50, 0xe3, 0x15, 0x98, 0xe8, 0x6e, 0x42, 0xd2,
	0x41, 0xee, 0x9b, 0xf0, 0x01, 0x1d, 0xbe, 0xe5, 0xba, 0x04, 0x19, 0x0d, 0x12, 0x92, 0xde, 0xcf,
	0xbb, 0x2e, 0x3c, 0xa5, 0x87, 0xbe, 0xca, 0x81, 0x5b, 0xac, 0xa2, 0xe1, 0xc6, 0x48, 0xbe, 0x93,
	0x85, 0x0f, 0xe9, 0x91, 0x15, 0x97, 0x30, 0xe7, 0x17, 0x60, 0xec, 0x46, 0xc0, 0xbd, 0x84, 0xa4,
	0x47, 0xf9, 0x6e, 0xf8, 0xf4, 0xf0, 0xe3, 0x72, 0x1c, 0x7c, 0x5e, 0x8e, 0x83, 0x5f, 0xcb, 0x71,
	0x30, 0x93, 0x5f, 0x57, 0x31, 0xb9, 0x5e, 0xc5, 0xe4, 0xe7, 0x2a, 0x26, 0x9f, 0xd6, 0x71, 0x70,
	0xbd, 0x8e, 0x83, 0x1f, 0xeb, 0x38, 0x78, 0xf5, 0x4c, 0x69, 0x77, 0xb9, 0x28, 0x98, 0xc0, 0x79,
	0xe6, 0x0d, 0x4e, 0xfe, 0x75, 0xde, 0xc9, 0xd6, 0xe1, 0xa4, 0x3b, 0xf0, 0xfb, 0xde, 0x89, 0x5d,
	0x53, 0x83, 0x2d, 0x86, 0xad, 0x9b, 0xc7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x41, 0x42,
	0x0f, 0xef, 0x02, 0x00, 0x00,
}

func (m *Validator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Validator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Validator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SchemaVersion != 0 {
		i = encodeVarintValidator(dAtA, i, uint64(m.SchemaVersion))
		i--
		dAtA[i] = 0x38
	}
	if len(m.JailedReason) > 0 {
		i -= len(m.JailedReason)
		copy(dAtA[i:], m.JailedReason)
		i = encodeVarintValidator(dAtA, i, uint64(len(m.JailedReason)))
		i--
		dAtA[i] = 0x32
	}
	if m.Jailed {
		i--
		if m.Jailed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Power != 0 {
		i = encodeVarintValidator(dAtA, i, uint64(m.Power))
		i--
		dAtA[i] = 0x20
	}
	if m.PubKey != nil {
		{
			size, err := m.PubKey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintValidator(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Description != nil {
		{
			size, err := m.Description.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintValidator(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintValidator(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintValidator(dAtA []byte, offset int, v uint64) int {
	offset -= sovValidator(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Validator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovValidator(uint64(l))
	}
	if m.Description != nil {
		l = m.Description.Size()
		n += 1 + l + sovValidator(uint64(l))
	}
	if m.PubKey != nil {
		l = m.PubKey.Size()
		n += 1 + l + sovValidator(uint64(l))
	}
	if m.Power != 0 {
		n += 1 + sovValidator(uint64(m.Power))
	}
	if m.Jailed {
		n += 2
	}
	l = len(m.JailedReason)
	if l > 0 {
		n += 1 + l + sovValidator(uint64(l))
	}
	if m.SchemaVersion != 0 {
		n += 1 + sovValidator(uint64(m.SchemaVersion))
	}
	return n
}

func sovValidator(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozValidator(x uint64) (n int) {
	return sovValidator(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Validator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValidator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Validator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Validator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Description == nil {
				m.Description = &Description{}
			}
			if err := m.Description.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PubKey == nil {
				m.PubKey = &types.Any{}
			}
			if err := m.PubKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Power", wireType)
			}
			m.Power = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Power |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Jailed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Jailed = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JailedReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JailedReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SchemaVersion", wireType)
			}
			m.SchemaVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SchemaVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipValidator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValidator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipValidator(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowValidator
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthValidator
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupValidator
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthValidator
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthValidator        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowValidator          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupValidator = fmt.Errorf("proto: unexpected end of group")
)
