@startuml
!pragma teoz true
hide footbox

actor Vendor as V
actor "Test House" as T
actor "ZigBee Certification" as ZB
actor User as U
entity Device as D
database Ledger as L

note over L
Setup PKI (see XXX):
- Root Certificate `RootCert`
- Vendor Certificate `VendorCert(vid. pid)`
end note

== 1. Setup Model Info ==
V -> L: Save `ModelInfo(vid, pid)`

== 2. Issue Device ==
D -> D: generate `privKey` and `pubKey`
D -> D: X509 Device Cert `DeviceCert(vid,pid)`\nwith `pubKey`, `vid`, `pid`
V -> D: Sign `DeviceCert` by `VendorCert(vid,pid)`

== 3. Test Device Compliance ==
T -> T: Run compliance tests for the `ModelInfo(vid, pid)`
T -> L: Save compliance test results for `vid` and `pid`

== 4.1. Attest Device Compliance ==
ZB <- L: Get compliance test results for `ModelInfo(vid, pid)`
ZB -> ZB: Check compliance test results
ZB -> L: Attest certification of `vid` and `pid`


== 4.2. Revoke Device Compliance ==
ZB -> L: Revoke certification of `vid` and `pid`

== 5. Use Device ==
U <- D: Get `DeviceCert(vid, pid)`
U <-> D: Verify proof of privKey possession
U <-- L: Get `VendorCert(vid. pid)`\n(update cache if needed)
U <-- L: Get `RootCert`\n(update cache if needed)
U -> U: Verify `DeviceCert(vid, pid)` signature
U -> U: Verify that `DeviceCert`'s `pid` and `vid`\nequals to `VendorCert`'s `pid` and `vid`
U <-- L: Get ZB Compliance results\n(update cache if needed)



@enduml