@startuml
!pragma teoz true
hide footbox

actor "ZA Trustee 1" as T1
actor "ZA Trustee N" as TN
database Ledger as L
actor "Node Admin" as NA

== Genesis Block ==
note over L
4 Node transactions
4 Accounts with NodeAdmin roles
end note

== Add a new validator node ==
NA -> NA: generate Account keys
NA -> T1: send account's pubKey
T1 -> L: propose a new Account with role=NodeAdmin and pubKey

alt if more than 1 Trustee signature is required for role NodeAdmin
    TN -> L: approve adding a new Account
end alt

L -> L: a new Account with role=NodeAdmin is created

NA -> NA: generate Node's key
NA -> L: add new validator Node with Node's pubKey

== Remove a validator node by Trustee(s) ==
T1 -> L: propose removing a Node

alt if more than 1 Trustee signature is required for revocation
    TN -> L: approve revocation
    TN -> L: approve revocation
end alt

L -> L: Node is removed
L -> L: Node's Account is removed

== Remove a validator node by NodeAdmin ==
U -> L: remove the node

== Rotate the node's key ==

U -> L: rotate the node's key

@enduml