#!/bin/bash
# Copyright 2020 DSR Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu
set -o pipefail

CONFIG_FILE="$HOME/.dcl/config/config.toml"
PERSISTENT_PEERS_FILE="${1:-./persistent_peers.txt}"
PERSISTENT_PEERS="$(cat $PERSISTENT_PEERS_FILE | head -n1)"

sed -i -r "s~^persistent_peers = .*~persistent_peers = \"$PERSISTENT_PEERS\"~" "$CONFIG_FILE"

echo "Updated"
