#!/bin/sh

DEBUG="${DEBUG:-}"

NODE_IP="${1:-0.0.0.0:26657}"

set -eu
set -o pipefail

export PATH="$PATH:/usr/bin"

echo "Checking the node 'sync_info.latest_block_height' value is not increasing..."

echo "sync_info.latest_block_height Try 1"
check1="$(dclcli status --node "$NODE_IP" | grep latest_block_height)"

echo "sync_info.latest_block_height Try 2"
sleep 6
check2="$(dclcli status --node "$NODE_IP" | grep latest_block_height)"

if [[ "$check1" == "$check2" ]]; then
    echo "Error: sync_info.latest_block_height value is not increasing..."
    exit 1
fi

# TODO improve
echo "Checking the node is participating in consensus..."
dclcli tendermint-validator-set | grep -q address

echo "Passed"
