---
# Copyright 2022 Samsung Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Check All Molecule tests
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths:
      - deployment/test-requirements.txt
      - deployment/ansible/roles/**
  pull_request:
    branches:
      - master
    paths:
      - deployment/test-requirements.txt
      - deployment/ansible/roles/**

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      bootstrap: ${{ steps.filter.outputs.bootstrap }}
      genesis: ${{ steps.filter.outputs.genesis }}
      add-accounts: ${{ steps.filter.outputs.add-accounts }}
      configure: ${{ steps.filter.outputs.configure }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        if: ${{ !env.ACT }}
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            reqs: &reqs
              - 'deployment/test-requirements.*'
            bootstrap:
              - *reqs
              - 'deployment/ansible/roles/bootstrap/**'
            genesis:
              - *reqs
              - 'deployment/ansible/roles/genesis/**'
            add-accounts:
              - *reqs
              - 'deployment/ansible/roles/add-accounts/**'
            configure:
              - *reqs
              - 'deployment/ansible/roles/configure/**'
  check-bootstrap:
    needs: changes
    if: needs.changes.outputs.bootstrap == 'true'
    name: Check Bootstrap Ansible role
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-molecule
        with:
          ansible-role: bootstrap
  check-genesis:
    needs: changes
    if: needs.changes.outputs.genesis == 'true'
    name: Check Genesis Ansible role
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-molecule
        with:
          ansible-role: genesis
  check-add-accounts:
    needs: changes
    if: needs.changes.outputs.add-accounts == 'true'
    name: Check Add accounts Ansible role
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-molecule
        with:
          ansible-role: add-accounts
  check-configure:
    needs: changes
    if: needs.changes.outputs.configure == 'true'
    name: Check Configure Ansible role
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-molecule
        with:
          ansible-role: configure
